Disable user attributes for active service
CESNET/perun-web-apps pull request #1003
Opened 2022-04-05 07:37 UTC by bodnara

* user related attributes are disabled when adding new required attributes to active service when consents are also required

2022-04-05 14:46 UTC, HejdaJakub requested changes
Due to the async call, the attr list in the add required attr dialog is a little bit inconsistent during the loading. For a few seconds, all items are loaded, but the check if some checkboxes should be disabled isn't completed yet. So I am able for a few seconds to check also checkboxes, which will be disabled soon. 
![image](https://user-images.githubusercontent.com/70371638/161779616-0be2982d-2ff0-4252-be6c-f9377ee84359.png)

2022-04-06 07:26 UTC, bodnara commented on apps/admin-gui/src/assets/config/defaultConfig.json
> +  "enforce_consent": false,
Unified.

2022-04-06 07:32 UTC, bodnara commented
> Due to the async call, the attr list in the add required attr dialog is a little bit inconsistent during the loading. 

I have set the default values to a "defensive" option and that it expects consents to be required. I also switch form `concatMap` to `mergeMap` to get `consentHub` for all facilities. It should be significantly faster as now calls can be done in parallel rather than always waiting for the previous to finish.

2022-04-06 08:42 UTC, HejdaJakub requested changes
Good job, it looks faster! 
I just realized one more thing. There can be a problem with the master toggle checkbox in the dialog. At this moment the `someCheckboxDiasabled` attribute is set to false (without `canBeSelected` method) so with the header checkbox, I can select also disabled checkboxes.

2022-04-07 09:19 UTC, HejdaJakub approved these changes

2022-04-07 09:39 UTC, merged