Tenant vos
CESNET/perun-web-apps pull request #1013
Opened 2022-04-11 16:35 UTC by bodnara

* added page for managing member organizations of hierarchical org.
* added dialog to add/remove member org.
* added new icon for hierarchical org.
* member/parent vos are included  on org. detail

2022-04-19 10:22 UTC, xkureck requested changes
Hello, so fix the space between the names of members vo, here is something that can help  you

https://www.tutorialrepublic.com/faq/how-to-remove-the-space-between-inline-block-elements-in-css.php

Also it would be nice if you used the universal remove dialog

2022-04-20 11:23 UTC, bodnara commented
Universal remove dialog was utilized.
Regarding the spacing, I couldn't find a simple solution and realized that this whole section is not very useful and should probably be removed anyway.

2022-04-25 09:04 UTC, xkureck requested changes
btw the stakeholders also wanted to have "tenant" icon in the list of all vos in the select vo table
![image](https://user-images.githubusercontent.com/32871167/165057022-c477e2f0-12e2-4194-b47c-3d05a258951f.png)

2022-04-25 09:04 UTC, xkureck commented on apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-member-organizations/vo-settings-member-organizations.component.ts
> +          this.reloadDetailService.reloadEntityDetail();
reload entity detail doesnt wait for remove member vos to end so the entity is reloaded with old data

2022-04-25 16:50 UTC, xkureck requested changes
this is really the last thing

2022-04-25 16:50 UTC, xkureck commented on apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html
> +          {{vo.shortName}},
```suggestion
          {{vo.shortName}}<span *ngIf="enrichedVo.memberVos.length !== 0 || enrichedVo.parentVos.length !== 0">, </span>
```

we don't want the "," here if there is no continuing

2022-04-26 09:55 UTC, xkureck approved these changes

2022-04-26 09:55 UTC, merged