feat(profile): accessibility features
CESNET/perun-web-apps pull request #1029
Opened 2022-05-11 10:42 UTC by bodnara

* application title is now also translated
* html lang attribute is set based on user preferred language
* added aria label to menu toggle button
* added title to header logo for screen readers

2022-05-11 13:15 UTC, mattjoke approved these changes

2022-05-11 15:15 UTC, xkureck commented on apps/user-profile/src/assets/i18n/cs.json
> +  "TITLE": "Uživatelskí profil",
```suggestion
  "TITLE": "Uživatelský profil",
```

2022-05-13 13:03 UTC, xkureck requested changes

2022-05-16 10:09 UTC, xkureck approved these changes

2022-05-16 10:09 UTC, merged