feat(admin): add member result handling
CESNET/perun-web-apps pull request #1040
Opened 2022-05-19 09:42 UTC by bodnara

* chnaged notification behaviour for adding members
* if all request end in success notification is shown
* if some request result in an error a list of candidates and the corespondig error are shown
* separated the container and the presenter part of add member dialog
* refactored files affected by this change

2022-05-19 10:59 UTC, xflord requested changes
A quick review since I just wanted to see how it all turned out, might look at it more Monday. Also, when searching for users I had some problems with the auto-search, where when I was searching different users in quick succession, my latest result would be overwritten after like a second by a search i did previously. However this was quite rare (Happened 2 times after like 30 minutes of trying to reproduce)

2022-05-19 10:59 UTC, xflord commented on apps/admin-gui/src/assets/i18n/en.json
>        "SUCCESS": "Selected members were added",
```suggestion
      "SUCCESS_ADD": "Selected members were added",
```
to match usage

2022-05-20 20:55 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/169603288-08c81389-cf0d-40e1-84a1-1265025604d5.png)
success notification is not working

![image](https://user-images.githubusercontent.com/32871167/169603380-420a1ccc-e456-4a54-9b9c-1d6ed2a01d16.png)
I just miss something in this dialog - I think this needs some sort of alert - alert about what I should do now

![image](https://user-images.githubusercontent.com/32871167/169608141-aa4908c8-07dd-4674-a3a6-49753642b1c4.png)
For this case maybe would be usable the error dialog.
Also the table should look somehow like a table like we have it in the other parts of the GUI, like this:
![image](https://user-images.githubusercontent.com/32871167/169608429-fccaaf2b-5e71-4307-9324-56aec2128839.png)
first column "name" and second "error"
Also I wouldn't put the name of the exception(eg. WrongReferenceAttributeValueException) like normal text - for user its really confusing
But I would put the name of the exception under the error message like this 
![image](https://user-images.githubusercontent.com/32871167/169609066-f73d8383-bc69-41d0-b742-ebaaffa69874.png)

Some of this may be unclear, or feels no right, so lets talk about it on daily

2022-05-23 09:44 UTC, bodnara commented
>Also, when searching for users I had some problems with the auto-search, where when I was searching different users in quick succession, my latest result would be overwritten after like a second by a search i did previously. However this was quite rare (Happened 2 times after like 30 minutes of trying to reproduce)

There was indeed a problem, that some previous request may take too long and override the data. Now each new request should cancel the previous one if it is not finished.

2022-05-24 09:20 UTC, xflord approved these changes

2022-05-24 15:16 UTC, xkureck requested changes
this is not whole review, just some visuals, I will continue with code, tomorrow

2022-05-25 14:05 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html
> +            [matTooltipDisabled]="!(memberCandidate | disabledCandidate: blockManualAdding)"
you can create new pipe for the get tooltip also, to get rid of the function in the html

2022-05-25 14:26 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html
> +        [matTooltipDisabled]="selection.selected.length === 0 || addAuth">
```suggestion
        [matTooltipDisabled]="selection.selected.length === 0 || inviteAuth">
```
this is tooltip for invite button

2022-05-25 14:27 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html
> +        [disabled]="selection.selected.length === 0 || !addAuth">
maybe we would like some sort of tooltip when this button is disable due to priviledges

2022-06-03 10:55 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/171833584-4bce4afd-caef-4b84-8190-e43c83ef61c3.png)
Not the scope of the feature - but please fix this so the disabled checkbox cant be checked by clicking on the select add checkbox - that's easy fix, just use different method/parameters in the method isAllSelected/masterToggle

2022-06-03 10:55 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html
> +          {{'DIALOGS.ADD_MEMBERS.CLOSE' | translate}}
when user click on this button, the table in the vo/group-members page don't refresh - but In this situation some members might be added but user don't see the added members

2022-06-08 10:55 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/172596447-fe02c1cf-2542-464b-9cd1-a52056dcf99f.png)

after this minor changes it can be merged

2022-06-08 10:55 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html
> +      <div mat-dialog-actions *ngIf="!loading">
move this div with mat-dialog-actions out of the div with mat-dialog-content - the close button is not on the right spot right now

2022-06-08 11:41 UTC, xkureck approved these changes

2022-06-08 11:41 UTC, merged