feat(admin): service propagation of expired members
CESNET/perun-web-apps pull request #1043
Opened 2022-05-20 12:38 UTC by Johaney-s

* added option to change service's usage of expired group members

2022-05-20 22:23 UTC, xkureck requested changes

2022-05-20 22:23 UTC, xkureck commented on apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
> +              {{service.useExpiredMembers ? "filter_alt_off" : "filter_alt"}}
Also please consistency - when its false then we want to show the icon for off - next to it is service status that is doing it this way, so I don't care what you will change, but just be consistent

2022-05-20 22:23 UTC, xkureck commented on apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
> +        </span>
```suggestion
            <button (click)="changeServiceStatus()" class="icon-button" mat-icon-button>
            <mat-icon class="align-bottom">
              {{service.enabled ? "check_circle_outline" : "block"}}
            </mat-icon>
          </button>
        </span>
        , {{'SERVICE_DETAIL.EXPIRED_MEMBERS' | translate}}:
        <span>
          {{service.useExpiredMembers ? ('SERVICE_DETAIL.PROPAGATED' | translate) : ('SERVICE_DETAIL.NOT_PROPAGATED' | translate)}}
          <button (click)="changeServiceExpiredMembersUsage()" class="icon-button" mat-icon-button>
            <mat-icon class="align-bottom">
              {{service.useExpiredMembers ? "filter_alt" : "filter_alt_off"}}
            </mat-icon>
          </button>
        </span>
        <span>
          , {{'SERVICE_DETAIL.EVALUATE_CONSENTS' | translate}}:
          <button (click)="evaluateConsents()" class="icon-button" mat-icon-button>
            <mat-icon class="align-bottom"> swipe_right_alt </mat-icon>
          </button>
        </span>
```
The suggestion is not 1 to 1 to the row
What about this? Does it look a little bit better? What do you think?

into the CSS file:
`.icon-button {
  line-height: inherit !important;
  width: inherit !important;
  height: inherit !important;
}
`

2022-05-23 06:43 UTC, Johaney-s commented on apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
> +              {{service.useExpiredMembers ? "filter_alt_off" : "filter_alt"}}
after we discussed the filter icon wasn't intuitive, the option to change the usage of expired members is now moved to the edit part. also discussed it with PO and it seems the service detail will be remade in a separate task, so for now i also kept the evaluate consents button the way it was

2022-05-23 08:01 UTC, xkureck approved these changes

2022-05-23 08:01 UTC, merged