feat(admin): support for HTML in notifications
CESNET/perun-web-apps pull request #1063
Opened 2022-06-09 19:08 UTC by HejdaJakub

* Now is possible to create new notification (or edit old notificaion) also in HTML format (not just plain text template).

2022-06-10 11:11 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/173046795-f76eb138-02c2-4884-89a4-e36f39b2a21e.png)
https://uxplanet.org/tabs-for-mobile-ux-design-d4cc4d9410d1
posible solution:
![image](https://user-images.githubusercontent.com/32871167/173050507-c3e8eb99-1afb-4e69-87b1-ec4162838dd0.png)
https://ux.stackexchange.com/questions/16281/elegant-simple-and-obvious-sub-tabs

![image](https://user-images.githubusercontent.com/32871167/173051924-bc550a08-0bd6-40ff-99fc-e2f11d6d476c.png)
Also, I and PO think that maybe some sort of information would be nice if they would be placed on place 1 or 2 - information about how this actually works:
- when the HTML notification is filled then this one will be sent to user, the plain notification will be used as a backup for the email clients that do not support HTML in email
- don't forget to change both(HTML + plain) formats when updating some of the formats

2022-06-13 15:29 UTC, bodnara requested changes
From a functional point of view other than the lable change I believe there was a requirement for validation of the HTML.

Now for the fun part. The dialog itself would benefit from some refactoring and decomposition as it handles a lot of logic.
Using the "container-presenter" pattern could separate the handling of `vo` and `group` specific actions while reusing the UI. You can look at how the `add-member-dialog` is split.
I would also suggest creating separate components for the language and notification "type" tabs respectively, to "lighten" the dialog itself. I know this type of refactor was not accounted for  but would be a huge improvement at least in my opinion.

From a UI standpoint:
Replace the label: text approach with a placeholders we commonly use (not 100% part of  this issue but a quick fix).
![image](https://user-images.githubusercontent.com/23495969/173388205-12c4710b-3b12-427a-b63f-a55a2084fffb.png)

Consider the possibility of not having each language as a new tab but having one tab for the content of notifications and changing the language there. It would remove the tabs nesting. Also because when the `tags` section is open it look very clutered.

2022-06-14 08:33 UTC, HejdaJakub commented on apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html
> +                label="{{'DIALOGS.NOTIFICATIONS_ADD_EDIT_MAIL.FORMAT_' + format | uppercase | translate}}">
Nice workaround. I changed it.

2022-06-14 08:46 UTC, HejdaJakub commented
Functional point: at this moment, we can skip the HTML validation (only Perun Admin has rights for HTML notification settings now).
Other points (UI improvements and refactor): we agreed with @bodnara that other points will be solved in the separate pull-request

2022-06-14 08:49 UTC, bodnara approved these changes

2022-06-14 09:32 UTC, merged