feat(admin): show entities of membership role on user roles page
CESNET/perun-web-apps pull request #1093
Opened 2022-07-20 12:01 UTC by Johaney-s

* only IDs of vos, groups, resources and facilities were shown so far
* now tables with these entities where user has membership role are shown

2022-07-20 12:05 UTC, Johaney-s commented
First commit contains not yet merged (https://github.com/CESNET/perun-web-apps/pull/1090) changes in roles page.
Membership and sponsorship roles will only show up if approaching roles page via admin gui -> my profile -> roles.
After merging https://github.com/CESNET/perun/pull/3657 it will also be visible in admin gui -> user's detail -> roles.

2022-07-21 12:07 UTC, xkostka2 requested changes
For some reason, when I am viewing any user's roles, the description above the tables is missing, while when going through My profile, it is displayed just fine. 
![image](https://user-images.githubusercontent.com/47856862/180208894-e861578b-70db-4016-b5e0-af8ed9265041.png)

2022-07-22 13:54 UTC, xkostka2 approved these changes

2022-07-25 11:48 UTC, xkureck approved these changes

2022-07-25 11:48 UTC, merged