feat(profile): consolidator user testing feedback
CESNET/perun-web-apps pull request #1106
Opened 2022-08-09 08:43 UTC by HejdaJakub

* Label identities changed to accounts accros user-profile.
* New column "mail" added to the table "Your linked accounts".

2022-08-10 08:27 UTC, bodnara requested changes

2022-08-10 08:27 UTC, bodnara commented on apps/user-profile/src/assets/i18n/en.json
>      "SUCCESSFULLY_ADDED": "Identity was successfully added",
```suggestion
    "SUCCESSFULLY_ADDED": "Account was successfully added",
```

2022-08-11 07:33 UTC, bodnara approved these changes

2022-08-11 12:00 UTC, xkureck approved these changes

2022-08-11 12:01 UTC, merged