feat(consolidator): consolidator user testing feedback
CESNET/perun-web-apps pull request #1107
Opened 2022-08-09 15:30 UTC by HejdaJakub

* Two cards were merget to on with white backgroud.
* Logo in header now redirects to home. In the header is now also logout button and the button with url to another application (user-profile).
* Linked accounts are now in rows, with email in brackets (if is available) and with remove button. This button opens already existing dialog.
* When linker is closed and result is OK, then we newly do not redirect user to result page, but we just reload home page.

BREAKING CHANGE: Three properties were added to the defaultConfig.json (is_devel, log_out_enabled
and profile_label_en)

2022-08-11 13:32 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/184132925-b621045b-d607-4fb2-8753-b2143aab4206.png)

Also is the BREAKING CHANGE necessary? All the added config properties are not breaking anything if they stay on their default values. A dunno, Just asking

2022-08-11 13:32 UTC, xkureck commented on apps/consolidator/src/assets/i18n/en.json
> +          "TITLE": "Remove user's account",
```suggestion
          "TITLE": "Remove account",
```

2022-08-16 14:19 UTC, HejdaJakub commented on apps/consolidator/src/app/components/connect-identity-section/connect-identity-section.component.ts
> +        window.location.reload();
Refactored - connect-identity component merged with main-window component, so now is easier to update data after some changes from linker

2022-08-16 14:20 UTC, HejdaJakub commented
> Also is the BREAKING CHANGE necessary? All the added config properties are not breaking anything if they stay on their default values. A dunno, Just asking
You are right, it's not probably necessary to mark it as a BREAKING CHANGE.

2022-08-17 10:41 UTC, xkureck approved these changes

2022-08-17 10:41 UTC, merged