feat(admin): update of the Table-Checkbox service
CESNET/perun-web-apps pull request #1128
Opened 2022-08-26 14:52 UTC by mattjoke

* updated TableCheckbox Service
* merged isAllSelected and isAllSelected isAllSelectedWithDisabledCheckbox
* changed the call for the service to be used
  in a pipe

2022-09-06 13:35 UTC, HejdaJakub requested changes
I don't know why, but replacing methods in HTML with pipes didn't fix the problem. We can discuss it on a daily standup.

2022-09-06 13:35 UTC, HejdaJakub commented on apps/admin-gui/src/app/shared/components/blacklist-list/blacklist-list.component.html
> +            [indeterminate]="selection.hasValue() && !(dataSource | isAllSelected: selection.selected.length :canBeSelected)"
Remove no existing method `canBeSelected`. This problem is in many places, so fix it in all HTML files, where this problem occurs, please.
![image](https://user-images.githubusercontent.com/70371638/188648282-f5a41d90-ae8c-4c1c-a655-f0d29ccf34ca.png)

```suggestion
            [checked]="selection.hasValue() && (dataSource | isAllSelected: selection.selected.length)"
            [indeterminate]="selection.hasValue() && !(dataSource | isAllSelected: selection.selected.length)"
```

2022-09-06 13:35 UTC, HejdaJakub commented on libs/perun/pipes/src/lib/is-all-selected.pipe.ts
> +    canBeSelected: (T) => boolean
Make this param optional, so you can skip it in HTML files, where this method does not exist.
```suggestion
    canBeSelected?: (T) => boolean
```

2022-09-21 09:20 UTC, bodnara requested changes
Some tables have console errors and some do not show properly at all, I did not go through all of them but e.g. the member-list.

Also perhaps it was not specified properly but the masterToggle function can have the number of parameters reduces as well.

2022-09-21 09:20 UTC, bodnara commented on libs/perun/pipes/src/lib/is-all-selected.pipe.ts
> +  }
```suggestion
  transform<T> (
    ds: MatTableDataSource<T>,
    numberSelected: number,
    canBeSelected?: (item: T) => boolean
  ): boolean {
    return this.tableCheckboxService.isAllSelected(numberSelected, ds, canBeSelected);
  }
```

2022-09-21 09:20 UTC, bodnara commented on libs/perun/services/src/lib/table-checkbox.service.ts
> +    canBeSelected?: (T) => boolean
If we provide a default select function that just returns true, there is no need for the `if(!canBeSelected)` block I believe.
```suggestion
    canBeSelected: (item: T) => boolean = (): boolean => true
```

2022-09-27 11:31 UTC, bodnara approved these changes
Nice job on this one.

2022-09-27 14:17 UTC, HejdaJakub approved these changes
I have bad news guys because I tested it and the function `isAllSelected()` from the tableCheckbox service is still called many times on every mouse move across the table. Then I found out that we call in these HTML files function `checkboxLabel()`, which calls `isAllSelected()` function and here we go again. But I believe that this part deserves a separate task and a separate PR so that I can approve this PR.

2022-09-29 07:17 UTC, merged