feat: catch mfa required error and handle mfa
CESNET/perun-web-apps pull request #1131
Opened 2022-09-07 10:35 UTC by HejdaJakub

* Now our applications catch new MFA required error.
* If this error occurs, then the first dialog is opened that tells the user, that MFA is required.
* If the user wants to proceed with additional verification, then is opened a new window, which handles MFA.
* Original window is locked until the second window is opened.

2022-09-15 09:04 UTC, xkostka2 approved these changes

2022-09-21 08:08 UTC, bodnara requested changes
Overall very well done. Just some small things to change.

2022-09-21 08:08 UTC, bodnara commented on libs/perun/multi-factor-authentication/src/lib/mfa-required-dialog/mfa-required-dialog.component.html
> +  <button (click)="onCancel()" class="ml-auto" mat-flat-button>
I believe one of angular stylistic suggestions is to not prefix with on.

2022-09-22 09:36 UTC, bodnara approved these changes

2022-09-23 07:38 UTC, merged