fix(admin): disable remove of indirect member in groups view
CESNET/perun-web-apps pull request #1160
Opened 2022-10-11 09:13 UTC by mattjoke

* indirect member in group table in member profile section, no longer allows removal of indirect members

2022-10-13 09:06 UTC, bodnara requested changes
The indirect tooltip is present even on places where it shouldn't.
![image](https://user-images.githubusercontent.com/23495969/195553809-42e1f7b2-8030-4bba-8e66-48e5ff3b5d01.png)

2022-10-19 11:21 UTC, mattjoke commented
It would be a good idea, to test the solution after the merge https://github.com/CESNET/perun/pull/3750

2022-10-25 13:31 UTC, bodnara approved these changes

2022-11-02 06:52 UTC, xflord approved these changes

2022-11-02 06:53 UTC, merged