feat(pwd-reset): configurable labels
CESNET/perun-web-apps pull request #1170
Opened 2022-10-25 13:16 UTC by bodnara

* added password labels to configuration
* changed password help to map
* allowed service access for pwd reset

2022-10-26 09:15 UTC, mattjoke reviewed
There are some misspellings, probably from earlier version, otherwise I think it looks good!

2022-10-27 07:17 UTC, bodnara commented
Translations were fixed. Also query parameters are now merged correctly after login.

2022-10-27 07:20 UTC, mattjoke approved these changes

2022-10-27 07:23 UTC, bodnara commented
Marked this  PR as breaking change since it changed configuration.

2022-10-27 14:32 UTC, HejdaJakub requested changes
- There is one use case when we want to correctly handle also errors in response from the backend - not only check when I am typing but also catch errors after sending a request for reset/activation - there is an infinitive loader. NOT only for `PasswordStrengthException`, but also for `LoginNotExistsException`.

![image](https://user-images.githubusercontent.com/70371638/198305098-ecedb35b-8582-4f9b-a3cd-771674abb7f0.png)
![image](https://user-images.githubusercontent.com/70371638/198304615-1b5978ab-ba60-44aa-82f4-bf1bc31bc332.png)

- I realized one more thing. There isn't a really good solution for how we parse mode from the URL - we parse any occurrence of a string in the whole URL - `this.mode = queryParams.includes('activation') ? 'activation' : 'reset';` - I know that the namespace like this probably doesn't exist (I hope), but we should parse it in some better way, something like this: `this.mode = parseQueryParams('mode', queryParams) === 'activation' ? 'activation' : 'reset';`
![image](https://user-images.githubusercontent.com/70371638/198308496-6e502c2b-ad28-4589-8c9b-fb96d3a80dcd.png)

- I know that this is not a part of your task, but if I log in by `service-access` with queryParams, everything looks good. But if I refresh the page, the queryParams are lost and I am not even able to type them back manually.

2022-10-27 14:32 UTC, HejdaJakub commented on apps/password-reset/src/app/pages/password-reset-page/password-reset-page.component.ts
> +import { PasswordAction, PasswordLabels } from '@perun-web-apps/perun/models';
'PasswordLabels' is defined but never used
```suggestion
import { PasswordAction } from '@perun-web-apps/perun/models';
```

2022-11-02 17:45 UTC, HejdaJakub requested changes
- It looks like there is still a problem with query params when I am logged in with service-access.
- I am not sure if we have some specific error on the backend for the use case when the account is already activated (IMHO we have), but I get this message also if the backend error is `PasswordStrengthFailedException` so in this case we probably do NOT inform the user correctly. I am not sure if the solution is just to modify the instance config to present a universal message for errors during the account activation or if we want to somehow deal with these errors separately. 
![image](https://user-images.githubusercontent.com/70371638/199560664-5992bb56-a821-423c-b8cf-2a1181a0a842.png)

2022-11-03 13:01 UTC, HejdaJakub reviewed
If we decide to fix `/service-access` and the `queryParams` in another PR, I will have just one last suggestoin / question (in the comment below).

2022-11-04 09:39 UTC, merged