fix(admin): expiration change dialog on the vo members list can no lo…
CESNET/perun-web-apps pull request #1174
Opened 2022-11-02 09:18 UTC by xflord

…nger be opened if user doesn't have rights to change member expiration

2022-11-03 10:35 UTC, bodnara requested changes

2022-11-03 10:35 UTC, bodnara commented on libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.ts
> +    if (!this.authResolver.isThisVoAdmin(this.voId)) return;
If possible please do this check with the `isAuthorized` method from `GuiAuthResolver`.

2022-11-07 07:27 UTC, bodnara requested changes
Right now the dialog will open even if user does not have rights to change status, because the async call is made but you don't wait for the result.
Anyway I believe you can get the vo/group from the EntityStoreService and just check for the rights when the members list is created. Also if user does not have rights to open this dilaog change the cursor on hover to default.

2022-11-07 07:29 UTC, bodnara commented on libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.ts
> +    if (!this.authResolver.isThisVoAdmin(this.voId)) return;
We have to make sure the correct policy is used for vo/group based on which page is the table used.

2022-11-07 09:53 UTC, bodnara approved these changes

2022-11-07 14:14 UTC, HejdaJakub approved these changes

2022-11-07 14:14 UTC, merged