feat(core): filter audit messages by event type
CESNET/perun-web-apps pull request #1193
Opened 2022-11-22 21:51 UTC by sarkapalkovicova

Added input for search string according to which messages will be filtered.

2022-11-23 07:15 UTC, bodnara commented
Has to be merged **AFTER** https://github.com/CESNET/perun/pull/3777

2022-11-30 07:35 UTC, Johaney-s reviewed
Looks good, not sure the changes in angular.json should be part of this pr. Could we have a "remove filter" button next to the selection? It might be easier to delete the selection that way than to scroll the list and search for the selected events while searching for another. What do you think?

2022-11-30 10:22 UTC, bodnara requested changes

2022-11-30 10:22 UTC, bodnara commented on apps/admin-gui/src/app/admin/pages/admin-page/admin-audit-log/admin-audit-log.component.html
> +    [selectPlaceholder]="'ADMIN.AUDIT_LOG.SEARCH_DESCRIPTION'|translate"></perun-web-apps-entity-search-select>
Entity search select is the base class for search select components. We don't use it directly but rather create a specification e.g. vo search select. I would like to ask if you could please create such a specification also for audit events.

2022-11-30 10:22 UTC, bodnara commented on apps/admin-gui/src/app/admin/pages/admin-page/admin-audit-log/admin-audit-log.component.ts
> +  secondaryTextFunction = (_: string): string => '';
As I mentioned, define these in the search select specification. There are also examples of methods that don't need the parameter.

2022-11-30 10:22 UTC, bodnara commented on apps/admin-gui/src/app/admin/pages/admin-page/admin-audit-log/admin-audit-log.component.ts
> +  }
Only propagate the changes after user closes the selection. That way we only refresh the table once users select all events they need. You can take a look of how it is done for selecting member status on vo member page.

2022-11-30 10:22 UTC, bodnara commented on libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
> +<mat-form-field class="{{ fullWidth ? 'w-100' : '' }}">
I understand why we would like this change but we can achieve this in little bit more elegant way. Keep the class here as before, but in the parent component put the the search select inside a container of fixed width (e.g. 450px). The search select will take up 100% of it's parent (here by parent I mean element like div). This way we don't need another input parameter.

2022-11-30 10:22 UTC, bodnara commented on libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
> -      .subscribe((entity: T) => this.entitySelected.emit(entity));
This code prevents emitting of the same value multiple times. This is quite important and can cause errors in some places. If you insist on removing it, make sure you handle it the onChange method.

2022-12-01 07:12 UTC, Johaney-s approved these changes

2022-12-14 10:36 UTC, bodnara approved these changes
Really good job.
I have one suggestion/question we have this notion of advaced filtering and there we have this button to clear the filters. Would it make sense to use the same one here ? If yes could you please change the icon and or the text here ? Otherwise this can be merged.
![image](https://user-images.githubusercontent.com/23495969/207572476-fcb0b697-e48d-42ad-8142-f11285884252.png)

2022-12-14 17:33 UTC, merged