feat(admin): add option to invite multiple members to Vo/Group at once
CESNET/perun-web-apps pull request #1197
Opened 2022-11-25 14:06 UTC by xflord

* added new dialog that allows invitation of multiple members via CSV
* update OpenAPI

2022-11-25 14:06 UTC, xflord commented
Merge after https://github.com/CESNET/perun/pull/3782

2022-11-26 16:58 UTC, Johaney-s requested changes
superb! :rocket: tested edge cases and it seems to be working well, only small suggestions from me.

2022-11-26 16:58 UTC, Johaney-s commented on apps/admin-gui/src/assets/i18n/en.json
> +      "DESCRIPTION_VO": "The persons you are inviting will receive an email with a link to organizations application form. You can set up an email template in: (Organization) Settings -> Notification
```suggestion
      "DESCRIPTION_VO": "The persons you are inviting will receive an email with a link to organization's application form. You can set up an email template in: (Organization) Settings -> Notifications.",
```
same with "group's" below

2022-11-26 16:58 UTC, Johaney-s commented on apps/admin-gui/src/assets/i18n/en.json
> +      "PLACEHOLDER": "'John;john@mail.cz' or 'john@mail.cz'",
```suggestion
      "PLACEHOLDER": "'john@mail.cz;John' or 'john@mail.cz'",
```

2022-11-26 16:58 UTC, Johaney-s commented on apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
> +        mat-flat-button>
```suggestion
        mat-menu-item>
```

2022-11-26 16:58 UTC, Johaney-s commented on apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html
> +        mat-flat-button>
```suggestion
        mat-menu-item>
```

2022-11-26 16:58 UTC, Johaney-s commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.html
> +          {{'DIALOGS.BULK_INVITE_MEMBERS.ERROR_FORMAT'| translate}}:
nitpick- if there are too many values inputted, the message can be confusing. maybe different alert should be used in that case.

2022-11-28 07:57 UTC, bodnara requested changes

2022-11-28 07:57 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.ts
> +  invitedMembers = new UntypedFormControl('', [Validators.required, this.userInputValidator()]);
Please use `FormControl` instead and after remove redundant type casting.

2022-11-28 07:57 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.ts
> +    this.languages = this.store.getProperty('supported_languages');
Don't duplicate the theme. Also assign the supported languages directly.

2022-11-28 07:57 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.ts
> +        }
Do we even need this check here ? It should not be possible to click on submit when the format is invalid.

2022-11-28 07:57 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.ts
> +    }
Here again if such case can happen, disable the download button instead.

2022-11-28 07:57 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.html
> +          >
```suggestion
          <mat-option *ngFor="let lang of languages" value="{{lang}}">
            {{'SHARED_LIB.LANGUAGES.'+lang | uppercase | translate}}
          </mat-option>
```

2022-11-28 07:57 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.html
> +    </button>
Now the cancel button is duplicated. We only need only div for the dialog actions and we can put the check on the buttons themself.

2022-11-28 07:57 UTC, bodnara commented on apps/admin-gui/src/assets/i18n/en.json
> +      "DESCRIPTION_VO": "The persons you are inviting will receive an email with a link to organizations application form. You can set up an email template in: (Organization) Settings -> Notification
Also
```suggestion
      "DESCRIPTION_VO": "The people you are inviting will receive an email with a link to organizations application form. You can set up an email template in: (Organization) Settings -> Notifications.",
```

2022-11-28 09:23 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/dialogs/bulk-invite-members-dialog/bulk-invite-members-dialog.component.ts
> +import { AbstractControl, FormControl, ValidatorFn, Validators } from '@angular/forms';
```suggestion
import { FormControl, ValidatorFn, Validators } from '@angular/forms';
```

2022-11-28 10:02 UTC, merged