feat: allow inputting multi-line string values to string attributes
CESNET/perun-web-apps pull request #1231
Opened 2023-01-20 09:44 UTC by xflord

* when changing/adding string attribute value, an edit icon is now present that opens a dialog with a text area that supports multi-line input
* when displaying a multi-line attribute value, show an indicator that it contains multiple lines (whole value is displayed upon clicking or opening the edit dialog)

2023-01-24 08:52 UTC, sarkapalkovicova approved these changes

2023-01-24 09:22 UTC, bodnara requested changes

2023-01-24 09:22 UTC, bodnara commented on libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.html
> +      matTooltip="Please use the edit button to edit multi-line string attributes"
Missing translation.

2023-01-24 09:22 UTC, bodnara commented on libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.ts
> +    this.editable = !this.readonly && !this.multiline;
Seems like `editable` is not used for anything and can be removed.

2023-01-24 09:22 UTC, bodnara commented on libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.ts
> +        `${values[0]} ... (${values.length - 1} more line` + (values.length > 2 ? 's)' : ')');
More lines indicator could also be localized.

2023-01-25 07:25 UTC, bodnara approved these changes

2023-01-27 08:39 UTC, balcirakpeter commented
We are waiting for feedback from other people.

2023-02-01 17:09 UTC, closed without merging