fix: migration to bootstrap 5
CESNET/perun-web-apps pull request #1234
Opened 2023-01-24 10:03 UTC by bodnara

Renamed the following classes
* left-* to start-*
* right-* to end-*
* ml-* to ms-*
* mr-* to me-*
* pl-* to ps-*
* pr-* to pe-*
* font-weight-* to fw-*

2023-01-24 11:00 UTC, mattjoke requested changes
Just skimmed through the files, however I think someone else needs also to look at this.

2023-01-24 11:00 UTC, mattjoke commented on libs/perun/dialogs/src/lib/member-tree-view-dialog/member-tree-view-dialog.component.html
>    <div *ngIf="!loading" mat-dialog-content class="mr-0">
```suggestion
  <div *ngIf="!loading" mat-dialog-content class="ms-0">
```

2023-01-24 11:00 UTC, mattjoke commented on libs/perun/components/src/lib/attribute-search-select/attribute-search-select.component.html
> +<div *ngIf="options !== undefined" class="container ml-0 mr-0 ps-0 pe-0 mt-3">
```suggestion
<div *ngIf="options !== undefined" class="container ms-0 me-0 ps-0 pe-0 mt-3">
```

2023-01-24 13:52 UTC, HejdaJakub requested changes

2023-01-24 13:52 UTC, HejdaJakub commented on apps/publications/src/app/pages/create-publication-page/import-publications-page/import-publications-page.component.html
> +      <button mat-stroked-button class="start-space" (click)="searchPublications()">
Again incorrect replacement. In this class is more similar cases like that for `start-space` and also for `end-button`.

2023-01-24 13:52 UTC, HejdaJakub commented on apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html
> +    <!--      class="ms-"-->
I know it's just a comment, but for consistency.
```suggestion
    <!--      class="ms-2"-->
```

2023-02-01 09:56 UTC, bodnara commented
- reverted changes to custom classes
- removed decorations on links
- aligned user name and menu in top header
- set proper display of icons inside button (refresh, back, ...)

2023-02-06 11:02 UTC, HejdaJakub approved these changes

2023-02-06 11:11 UTC, merged