feat: adjust the mat-button mat-card, mat-checkbox, mat-chips and mat-dialog components after upgrade to angular 15
CESNET/perun-web-apps pull request #1247
Opened 2023-01-31 12:53 UTC by xflord

2023-02-02 16:10 UTC, HejdaJakub requested changes
The ellipsis is not working in mat-chip:
![image](https://user-images.githubusercontent.com/70371638/216340583-a97a96c2-b7e3-43ad-873c-19100361c81a.png)

2023-02-03 11:06 UTC, xflord commented on libs/perun/components/src/lib/refresh-button/refresh-button.component.html
> +  mat-icon-button
The aligning of icons in buttons without text (unless its an icon button) is all messed up now. I spent a whole day trying to fix it and didn't manage to find a sensible solution. Will try a bit more though

2023-02-03 11:10 UTC, xflord commented on apps/admin-gui/src/app/shared/components/dialogs/add-facility-owner-dialog/add-facility-owner-dialog.component.html
> +    </div>
There are elements in which the filter stays on top, eg. the dialog for adding a new attribute (which is more user-friendly in my opinion). If we want to unify this then a new task should be made, however, I heavily lean towards this variant.

2023-02-06 09:38 UTC, xflord commented
Fixed the buttons. Pretty sure the correct version of chips is on my computer at the office; I will stop by in the afternoon and fix it then.

2023-02-06 15:42 UTC, xflord commented
Didn't manage to make the chips component (attribute value list) flexible as before even after racking my brains for 2 days already, I've fixed the ellipsis and made the width static for now (so we can potentially merge this PR and fix it later)

2023-02-07 12:40 UTC, HejdaJakub requested changes

2023-02-07 12:40 UTC, HejdaJakub commented on libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html
> +  <mat-form-field *ngIf="!readonly" subscriptSizing="dynamic" class="w-100">
On this page is an error when the attribute is read-only due to required `matChipInputFor` for `mat-chip-grid`.
![image](https://user-images.githubusercontent.com/70371638/217239094-6cadb568-5740-49ad-97ab-0b860b574dfd.png)
You can just replace `*ngIf` by `[hidden]` and it should work correctly.
```suggestion
  <mat-form-field [hidden]="readonly" subscriptSizing="dynamic" class="w-100">
```

2023-02-07 12:40 UTC, HejdaJakub commented on libs/perun/components/src/lib/back-button/back-button.component.html
> +  <mat-icon class=" ml-auto rotate">arrow_right_alt</mat-icon>
Again now it looks the same without this class I think.
```suggestion
  <mat-icon class="rotate">arrow_right_alt</mat-icon>
```

2023-02-07 14:17 UTC, xflord commented
Fixed what you mentioned along with checkbox labels that were affected by a new global CSS style

2023-02-09 07:40 UTC, HejdaJakub approved these changes

2023-02-09 08:11 UTC, merged