feat(apps): user roles are split by source
CESNET/perun-web-apps pull request #1248
Opened 2023-01-31 15:13 UTC by Kuliak

* user-detail page splits his roles by source (directly assigned or obtained as a member of authorized group)
* tabs added to change what source we want to see
* authorized-group-based roles cannot be managed, only viewed

2023-02-01 09:48 UTC, Johaney-s reviewed
It seems myProfile -> roles view is not working properly yet:
![image](https://user-images.githubusercontent.com/73999257/216008006-e9fdc959-8f59-4bae-961a-c3a34928e7a3.png)

and just a thought, but it might be too much work for such little thing, showing which authoritative group is giving us the role could be useful.

2023-02-01 18:49 UTC, xflord approved these changes
Remove the now unused imports, otherwise looks good, good job

2023-02-01 18:49 UTC, xflord commented on apps/admin-gui/src/assets/i18n/en.json
> +      "AUTHORIZED_GROUP_BASED_ROLES": "Authorized-group-based"
Would prefer it without the dashes

2023-02-15 14:39 UTC, xflord commented on libs/perun/services/src/lib/role.service.ts
> +  prepareComplementaryObjects(
please add javadocs

2023-02-17 09:28 UTC, xflord requested changes

2023-02-17 09:28 UTC, xflord commented on apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
> +              [voWithAuthzGroupPairs]="_complementaryObjectsWithAuthzGroups.get(role.roleName).get('vo')">
This causes exceptions in the user based tab.

2023-02-17 10:48 UTC, bodnara requested changes

2023-02-17 10:48 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
> +          *ngIf="editable"
Nitpick but the proper target should be the parent of the button (span tag). Right now the span is present so the tooltip could be triggered.

2023-02-17 10:48 UTC, bodnara commented on apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.ts
> +
While this works a better solution (without rxjs magic) would be to nest these calls. Also stop the loading if some of the requests fail.

2023-02-17 10:48 UTC, bodnara commented on libs/perun/components/src/lib/facilities-list/facilities-list.component.html
> +        </td>
I prefer the empty string for the else clause.

2023-02-17 10:48 UTC, bodnara commented on libs/perun/components/src/lib/facilities-list/facilities-list.component.ts
> +  }
It is not technically wrong to use input setter like this, it is more useful when there is a peace of code that needs to run every time the input changes. However to stay consistent with the rest of the codebase could you please make these a simple `@Input`. This goes for other list components.

2023-02-20 12:58 UTC, xflord reviewed
fix the scope to feat(admin) since the roles page is only in the admin gui

2023-02-20 12:58 UTC, xflord commented on apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.ts
> +                );
```suggestion
                .subscribe({
                  next: (obtainedComplementaryObjects) => {
                    // prepare map
                    this.rolesComplementaryObjectsWithAuthzGroups =
                      this.roleService.prepareComplementaryObjects(
                        Object.keys(obtainedComplementaryObjects),
                        obtainedComplementaryObjects
                      );
                    this.outerLoading = false;
                  },
                  error: () => (this.outerLoading = false)
                });
```
use the non-deprecated syntax with all the subscribe methods please (like this I believe)

2023-02-20 13:48 UTC, xflord approved these changes

2023-02-20 14:41 UTC, bodnara reviewed
There is some uninitialized value in the group-list on user based tab.
![image](https://user-images.githubusercontent.com/23495969/220136457-61fc07b0-a502-41a7-90cf-32f7cd076244.png)

2023-02-20 15:35 UTC, bodnara approved these changes

2023-02-21 11:43 UTC, merged