feat: allow inputting multi-line string values to string attributes
CESNET/perun-web-apps pull request #1249
Opened 2023-02-01 17:09 UTC by xflord

2023-02-02 07:44 UTC, HejdaJakub commented on libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.scss
> +.mat-form-field:not(.mat-focused) .mat-hint {
I will have to change this component (fix the UI on global level) in my PR on migration to MDC, but at least this comment for this local scss file will be useful.
NOTE: I used `mat-hint` without the dot (`.`) on purpose, but if we want to use class definition, then we can use this one in Angular 15: `.mat-mdc-form-field-hint`.
```suggestion
// FIXME: After the migration to MDC and Angular 15 have to be replaced the line below
// .mat-mdc-form-field:not(.mat-focused) mat-hint {
.mat-form-field:not(.mat-focused) .mat-hint {
```

2023-02-02 08:15 UTC, HejdaJakub approved these changes

2023-04-27 09:28 UTC, HejdaJakub requested changes
1) We have had ellipsis for long text/smaller screens since there was input, but for the textarea ellipsis doesn't work and it doesn't look very well (especially for single line non-editable attributes).
![image](https://user-images.githubusercontent.com/70371638/234819170-2dd88e52-d427-4b93-962c-bdd80a03e618.png)

2) I would also fix CSS for vertical mover - it is probably caused by our custom global CSS for attributes.
![image](https://user-images.githubusercontent.com/70371638/234820047-5fc2e86b-cd8a-4fd1-b20d-22f7f1736b3b.png)

It is weird when the mover is exactly on the bottom line and I believe it should look like e.g. in notifications:
![image](https://user-images.githubusercontent.com/70371638/234820491-4bec4ce5-cbfd-4126-8a04-7c419fd72889.png)

2023-05-05 07:15 UTC, xflord commented
TODO: check whether multine attribute values get correctly propagated to LDAP

2023-05-05 07:15 UTC, bodnara approved these changes

2023-05-15 06:56 UTC, mattjoke approved these changes

2023-05-17 09:29 UTC, HejdaJakub commented
@xflord tested the propagation to LDAP and it works

2023-05-17 09:30 UTC, merged