refactor(admin): use date-range component from Angular material
CESNET/perun-web-apps pull request #1257
Opened 2023-02-07 15:30 UTC by xkostka2

* picking date range using 2 date pickers has been replaced by single date-range component from Angular material

2023-02-08 08:38 UTC, bodnara requested changes
The date range could also be used in the `YearRangeComponent` or maybe these two could be merged to one component.

2023-02-08 08:38 UTC, bodnara commented on libs/perun/components/src/lib/date-range/date-range.component.ts
>    @Input() endDate: UntypedFormControl;
Please, change the Form Controls to the typed variant.

2023-02-09 08:18 UTC, xflord reviewed
![Screenshot from 2023-02-09 09-15-53](https://user-images.githubusercontent.com/97669007/217755206-305d3b62-9571-41d9-84cd-fe51c7744c51.png)
When choosing only the start date and clicking away, the table refreshes and shows this, which to me looks like results from the start date forward should be displayed (but that's not the case, nothing is displayed)

2023-02-09 13:15 UTC, xflord approved these changes

2023-02-14 08:12 UTC, bodnara approved these changes

2023-02-14 08:39 UTC, merged