feat: improve loading of dialogs and tables
CESNET/perun-web-apps pull request #1264
Opened 2023-02-20 11:27 UTC by HejdaJakub

* Two new loader components were created and used across all apps (LoadingTableComponent and LoadingDialogComponent).
* The use case when some dialog includes also table was checked and it should work correctly (only one spinner should be visible).
* Another possible candidates for new loader components are "entity-detail-page" and "overview" components, but it is usually not possible to display some data (data are not fetched yet) during the loading behind the spinner for these components. Since it is not about UX but only about "consistency" or possible future easier changes, I did not implemented it in this PR.

2023-02-20 16:42 UTC, xkostka2 requested changes
I found a minor consistency issue in the user profile app. On the Organisations page, there is a loader for each table separately, but on the Linked accounts page, there is just one loader for the whole page, even tho this page also contains multiple tables.

2023-02-21 09:28 UTC, xflord commented on .eslintcache
> +[{"/home/hejda/perun-web-apps/apps/admin-gui/src/app/admin/admin-routing.module.ts":"1","/home/hejda/perun-web-apps/apps/admin-gui/src/app/admin/admin.module.ts":"2","/home/hejda/perun-web-apps/apps/
remove this please

2023-02-21 09:40 UTC, xflord commented
![Screenshot from 2023-02-21 10-37-57](https://user-images.githubusercontent.com/97669007/220307211-a6319439-4dae-4766-8313-7a7f5d8c79a3.png)
IMO the 'no entities found' warning should not be visible during loading

2023-02-21 10:18 UTC, xflord commented
![Screenshot from 2023-02-21 11-15-30](https://user-images.githubusercontent.com/97669007/220316518-bb577296-3873-40a1-b0ab-b18765a5d789.png)
![Screenshot from 2023-02-21 11-12-42](https://user-images.githubusercontent.com/97669007/220316526-4a80e39c-7dab-4fbb-9cfe-96b9825cad06.png)
I would probably also limit the 'greyed out area' of the dialogs to dialog content only, the greyed out buttons and title looks weird to me (and is inconsistent with how dialogs with tables act)

2023-02-21 10:47 UTC, xflord commented
![Screenshot from 2023-02-21 11-47-04](https://user-images.githubusercontent.com/97669007/220324266-6a63f5e9-febc-4221-bd21-9a7187d21965.png)
The spinners in publication-detail component still replace the content

2023-02-21 10:48 UTC, xflord commented
That's all I found for now

2023-02-22 15:15 UTC, HejdaJakub commented
Discussion on Daily:
- for this moment we want to let a visible warning (empty table) during the initial loading
- the special use case for publication detail we want to skip for this moment
- we want to have a different spinner for a table in the dialog and for the whole dialog (already implemented), but the screenshot, where the dialog looks disabled just partly during the loading (without gray margins), was taken in firefox. This is due to firefox's default setting (for `:has()` CSS pseudo-class) which is criticized by the community and hopefully will be changed soon. So, we can use some workaround, which probably can be handled only with some javascript to add class dynamically, or we can hope that this default setting will be changed soon for firefox.
![image](https://user-images.githubusercontent.com/70371638/220632476-3366df79-fd22-4647-aa70-f14762db2e33.png)
![image](https://user-images.githubusercontent.com/70371638/220635799-b15fc6a2-5440-4ac2-b67c-5c0e5c038593.png)

2023-02-22 15:34 UTC, HejdaJakub commented
Fixed pages `identities-page` and `groups-page` and deleted file `.eslintcache`.

2023-02-23 10:04 UTC, xflord approved these changes
Fix the imports please, otherwise look good to me

2023-02-23 10:04 UTC, xflord commented on apps/user-profile/src/app/pages/groups-page/groups-page.component.ts
> +import { finalize, map, startWith, tap } from 'rxjs/operators';
Unused imports

2023-02-23 11:47 UTC, mattjoke approved these changes
Apart from changes mentioned above, I haven't found anything.

2023-02-23 16:53 UTC, merged