feat(admin): e2e login command
CESNET/perun-web-apps pull request #1307
Opened 2023-04-24 21:05 UTC by sarkapalkovicova

Added and used new custom command for login.

2023-04-25 07:21 UTC, mattjoke requested changes
I'm unsure about that line I mentioned in the comment before. Otherwise, the code looks good.

2023-04-25 14:39 UTC, HejdaJakub commented on apps/admin-gui-e2e/src/support/commands.ts
> +  sessionStorage.setItem('basicUsername', Cypress.env('BA_USERNAME' + envRole) as string);
It should be achievable like this (the same also for the password).
```suggestion
  sessionStorage.setItem('basicUsername', String(Cypress.env('BA_USERNAME' + envRole)));
```

2023-04-26 07:06 UTC, mattjoke approved these changes
Looks good 👍

2023-04-26 08:56 UTC, xflord approved these changes
well done

2023-04-26 13:29 UTC, merged