feat: replace mat-flat-button by mat-stroked-button
CESNET/perun-web-apps pull request #1353
Opened 2023-06-23 12:18 UTC by xkostka2

* all occurrences of mat-flat-button have been replaced by mat-stroked-button if button does not have background

2023-06-26 08:35 UTC, bodnara requested changes
Missing `NewVersionDialogComponent` and `ShowNotificationHistoryDialogComponent`.

2023-06-26 11:43 UTC, Kuliak reviewed
What about file **`tag-section.component.html`** ?

2023-06-27 07:05 UTC, bodnara approved these changes

2023-06-27 12:33 UTC, mattjoke approved these changes
Just need to rebase, otherwise it's good

2023-06-28 10:20 UTC, merged