ci: upgrade notes
CESNET/perun-web-apps pull request #1362
Opened 2023-07-11 13:46 UTC by xkostka2

2023-07-17 08:53 UTC, melanger commented on .releaserc.json
> -        "npmPublish": false
Keep npm, it increments version number in package.json

2023-07-17 08:53 UTC, melanger commented on .releaserc.json
> +        "assets": ["UPGRADE.md"],
Keep "dist"

2023-07-17 08:54 UTC, melanger commented on .releaserc.json
> -    "@semantic-release/github"
Keep, it creates GitHub release

2023-07-17 08:54 UTC, melanger commented on .releaserc.json
> -    { "name": "alpha", "prerelease": true },
IMHO you can keep alpha and beta

2023-07-17 08:55 UTC, melanger commented on package.json
> +    "@commitlint/cli": "^17.6.6",
Put these dependencies into devDependencies (`npm install --save-dev ...`)

2023-07-17 08:59 UTC, melanger commented on .github/workflows/semantic-release.yml
> +name: Semantic release
Do not create this file, release.yml already exists

2023-07-18 10:59 UTC, melanger requested changes

2023-07-18 10:59 UTC, melanger commented on package.json
> +    "semantic-release": "^21.0.7"
```suggestion
    "zone.js": "0.11.4"
```

remove this and run `npm update` to refresh package-lock.json

2023-07-18 14:23 UTC, melanger approved these changes

2023-07-19 10:58 UTC, mattjoke commented
Please change the node version to `lts/*` in release.yml, so it does not fail with the new versions of the semantic realease.

2023-07-19 11:28 UTC, HejdaJakub approved these changes

2023-07-19 11:28 UTC, merged