fix(admin): icon button tooltip
CESNET/perun-web-apps pull request #1368
Opened 2023-07-20 17:47 UTC by sarkapalkovicova

Added tooltip for every mat-icon-button.

2023-07-24 11:49 UTC, michalberky commented on apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html
I think it would be best to also move the tooltip from lines 106 and 107 of this file inside of the <button> tag starting on line 108. This would make the tooltip appear above the button where it should be.

2023-07-25 08:17 UTC, HejdaJakub requested changes
I think that the last place where the tooltip is missing is:
`perun-web-apps/apps/consolidator/src/app/components/list-of-identities` for the `<mat-icon>clear</mat-icon>`.
There is already a tooltip for the disabled icon, but there is no tooltip for the enabled one, so can you please add also a tooltip for the enabled icon?

2023-07-25 08:23 UTC, mattjoke approved these changes
Looks good :+1:

2023-07-25 08:28 UTC, michalberky approved these changes

2023-07-25 12:02 UTC, HejdaJakub approved these changes

2023-07-25 12:03 UTC, merged