fix(admin): notifications sending enabled control changed to toggle
CESNET/perun-web-apps pull request #1399
Opened 2023-08-18 07:56 UTC by kofzera

2023-08-18 10:10 UTC, xflord requested changes
Looks good, but part of the task was also to add a success notification when the 'sending setting' changes (similarly as a notification pops up when you add/remove entities). You can do this using the `NotificatorService`

2023-08-20 09:27 UTC, kofzera commented
> Looks good, but part of the task was also to add a success notification when the 'sending setting' changes (similarly as a notification pops up when you add/remove entities). You can do this using the `NotificatorService`

Somehow forgot about that, should be there now :smile:

2023-08-21 08:25 UTC, bodnara commented on apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.ts
> +          this.notificator.showSuccess(this.disabledSendingMessage);
Preferably use the `showInstantSuccess` method of the notificator. It handles the translation itself.

2023-08-21 10:45 UTC, sarkapalkovicova commented
In `add-edit-notification-dialog` is also used a checkbox. Shouldn't be here toggle too? @bodnara

2023-08-21 10:53 UTC, bodnara commented
> In `add-edit-notification-dialog` is also used a checkbox. Shouldn't be here toggle too? @bodnara

In this case checkbox is better option, since the action requires conformation (click on save button). In case of immediate action toggle is preferable.

2023-08-21 10:56 UTC, sarkapalkovicova approved these changes

2023-08-22 06:57 UTC, merged