feat(admin): jump onto specific page
CESNET/perun-web-apps pull request #1425
Opened 2023-09-19 06:58 UTC by sarkapalkovicova

Added input for inserting a wanted page number.

2023-09-19 09:29 UTC, michalberky requested changes
- The input field is not vertically aligned with rest of the table controls.

![Screenshot from 2023-09-19 11-07-38](https://github.com/CESNET/perun-web-apps/assets/87857076/abc93123-62d4-400f-ab11-1f8a8aa28a8d)


- I was also thinking if we need two sets of buttons incrementing the current page by one - the 'Previous page' and 'Next page' buttons that were already there and the arrows incrementing the number (although those only change the page on change of focus)
- I feel like possibility to confirm the new page number by pressing enter as well, instead of just focus loss, would be more intuitive
- Currently when editing the number, I can move cursor with mouse but can't with arrow keys. Also removing numbers is only possible with backspace and not with delete.

2023-09-19 13:42 UTC, sarkapalkovicova commented
> * The input field is not vertically aligned with rest of the table controls.
> 
> ![Screenshot from 2023-09-19 11-07-38](https://user-images.githubusercontent.com/87857076/268908115-abc93123-62d4-400f-ab11-1f8a8aa28a8d.png)
> 
> * I was also thinking if we need two sets of buttons incrementing the current page by one - the 'Previous page' and 'Next page' buttons that were already there and the arrows incrementing the number (although those only change the page on change of focus)
> * I feel like possibility to confirm the new page number by pressing enter as well, instead of just focus loss, would be more intuitive
> * Currently when editing the number, I can move cursor with mouse but can't with arrow keys. Also removing numbers is only possible with backspace and not with delete.

Arrows in input just increment the number that is inserted. Out previous/next page buttons immediately reload data. For me, these are 2 different things, but if you insist, I can hide arrows in input.  
I  am not sure if we use confirmation by enter somewhere in the GUI. Do we want that? @bodnara

2023-09-19 13:52 UTC, michalberky commented
> Arrows in input just increment the number that is inserted. Out previous/next page buttons immediately reload data. For me, these are 2 different things, but if you insist, I can hide arrows in input.

I don't insist 😄  It was just something I wanted to point out to maybe give another thought, but I see the difference and it can definitely stay that way.

The other things I mentioned are something I thought could help intuitivity, but in the end, as you say, it depends on how they are treated elsewhere to keep consistency.

2023-09-19 16:55 UTC, xflord approved these changes

2023-09-19 16:55 UTC, xflord commented on libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
> +      charCode === 65 || charCode === 66 || charCode === 68 || (charCode >= 48 && charCode <= 57)
Either use literals or describe what this does in a comment

2023-09-19 16:55 UTC, xflord commented on libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
> +      selectedPage = 1;
Staying on the current page makes more sense to me than going to 1, no?

2023-09-19 16:55 UTC, xflord commented on libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
> +      charCode === 65 || charCode === 66 || charCode === 68 || (charCode >= 48 && charCode <= 57)
Also why are A B and D allowed? I guess for some shortcuts? In that case allow them in combination with `CTRL`? This whole check seems unnecessary, IMO resetting the input if invalid value was put in would be enough, but up to you.

2023-09-19 16:57 UTC, xflord requested changes
missclick

2023-09-20 10:53 UTC, xflord approved these changes
LGTM

2023-09-20 11:06 UTC, bodnara reviewed
With the media query for smaller displays the number of page is not visible.
![image](https://github.com/CESNET/perun-web-apps/assets/23495969/20ce2710-4d7d-40b3-b61f-341270da171d)

We can do confirm with enter `(keyup.enter)="changePage($event)"`

2023-09-20 11:15 UTC, michalberky approved these changes

2023-09-20 16:08 UTC, sarkapalkovicova commented
> With the media query for smaller displays the number of page is not visible. ![image](https://user-images.githubusercontent.com/23495969/269262277-20ce2710-4d7d-40b3-b61f-341270da171d.png)
> 
> We can do confirm with enter `(keyup.enter)="changePage($event)"`

It seems to be different between browsers. I extended the input a little bit.

2023-09-21 07:02 UTC, bodnara approved these changes

2023-09-21 07:19 UTC, merged