fix(user-profile): removed unused calls
CESNET/perun-web-apps pull request #1461
Opened 2023-11-03 10:32 UTC by mattjoke

- removed unused calls for enitityless attributes
- fixed no-categories refresh bug

2023-11-06 15:12 UTC, HejdaJakub requested changes
I believe this way it should work correctly (tested for e-infra instance). Just a few suggestions.

It's really confusing to still have the `enforce_mfa_attribute` config property since the attribute stored in this property does not exist anymore and we are using just the part, where the instance type is defined. I would definitely replace this property with another more clear one (if we do this, the commit shall be marked as BREAKING CHANGE then). 

The `saveSettings` method also has an unused parameter `newEnforce`.

2023-11-07 10:20 UTC, xflord approved these changes

2023-11-07 10:20 UTC, xflord commented on libs/perun/services/src/lib/mfa-api.service.ts
> +    const categroriesLength = Object.keys(settings.categories).length;
typo

2023-11-08 07:15 UTC, HejdaJakub approved these changes

2023-11-08 07:16 UTC, merged