Authorization member section
CESNET/perun-web-apps pull request #422
Opened 2020-08-24 08:35 UTC by bodnara

Resolves #397 

Added authorization for:
* Overview - items, expiration attribute (authorization for this attr. is hardcoded for now)
* Sidemenu items
* Groups - Add/Remove buttons, routing, Add dialog (display of group)
* Resources - Add button, routing, Add dialog (disabled selection)
* Attributes - attribute list now disables checkbox and input for attributes that user cannot edit, on hover a hint is displayed

2020-08-25 19:36 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/91218569-8896bc00-e719-11ea-904e-ecbaa51eba29.png)

Authorization in Overview, Groups, Applications and Resources pages does not work at all.

2020-08-26 07:54 UTC, bodnara commented
> Authorization in Overview, Groups, Applications and Resources pages does not work at all (tested on a member without any admin privileges).

I am not sure, how did you manage to get to those pages as a member without any privileges. Could you give more information on how to recreate this problem? When I tried to access those pages as a member, it was not possible to get there without manually typing the URL. And even when then it worked properly. 
![image](https://user-images.githubusercontent.com/23495969/91276630-173f2380-e782-11ea-9587-b602597ff13b.png)

2020-08-26 08:33 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/91279630-02648f00-e786-11ea-8caa-024e54db093f.png)
As Vo observer I can get into the member detail but also I see the edit button for expiraton, vo observer doesnt have rights to change it so hide it if the user dont have the rights.
![image](https://user-images.githubusercontent.com/32871167/91279829-4b1c4800-e786-11ea-889b-b07203f04689.png)
The position of tooltip where it is saying that I dont have proper rights to change the attribute is very weird.
![image](https://user-images.githubusercontent.com/32871167/91280676-5d4ab600-e787-11ea-90ad-5278b34003b5.png)
The group manager can see member detail too but cannot add groups to the meber, the priviledge exception occurs.

2020-08-26 11:54 UTC, xkostka2 commented
> > Authorization in Overview, Groups, Applications and Resources pages does not work at all (tested on a member without any admin privileges).
> 
> I am not sure, how did you manage to get to those pages as a member without any privileges. Could you give more information on how to recreate this problem? When I tried to access those pages as a member, it was not possible to get there without manually typing the URL. And even then it worked properly.
> ![image](https://user-images.githubusercontent.com/23495969/91276630-173f2380-e782-11ea-9587-b602597ff13b.png)

When I tried it today, the pages seem to be working correctly. Maybe the problem was on my side, however, I did not change anything.

But still, shouldn't the user be able to see the member attributes page settings when he has privileges to manage them? 

![image](https://user-images.githubusercontent.com/47856862/91299015-4618c200-e7a1-11ea-9a88-166832df50de.png)

2020-08-26 12:02 UTC, xkostka2 commented
![image](https://user-images.githubusercontent.com/47856862/91300746-14edc100-e7a4-11ea-874a-c4859026457d.png)

![image](https://user-images.githubusercontent.com/47856862/91300781-220ab000-e7a4-11ea-9b31-1dabcc7836bd.png)

I also suggest not to hide "Save" and "Remove" buttons when selection is empty, but instead let them disabled.

2020-08-31 09:17 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/91694955-af1b8380-eb6d-11ea-9344-d8dc55e1fe9f.png)
Bug when I click on attributes the settings item in side menu would expand.

2020-08-31 09:17 UTC, xkureck commented on apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts
> +    protected router: Router,
you dont use it anywhere

2020-08-31 09:17 UTC, xkureck commented on libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts
> +       console.log(this.expirationAttr.writable);
I guess this log can be removed

2020-08-31 09:17 UTC, xkureck commented on libs/perun/components/src/lib/groups-list/groups-list.component.ts
> +    }
would probably move this piece of code to some more proper function, or place

2020-08-31 12:05 UTC, xkureck approved these changes

2020-08-31 12:06 UTC, merged