Authorization Facility section
CESNET/perun-web-apps pull request #424
Opened 2020-08-25 09:58 UTC by bodnara

Resolves #395 

Added authorization for:

* Overview - items
* Sidemenu - items
* Resources - Add/Remove buttons, routing
* Allowed groups - routing (routing is enabled/disabled specifically for each item in table)
* Service status - buttons
* Service config - this should be working properly once attribute-list changes are approved
* Service destinations - buttons
* Hosts - buttons, routing, host detail should work properly with attribute-list update
* Security teams - buttons (buttons are disabled for now)
* Attributes - ..attribute-list update
* Owners - buttons
* Managers - buttons

2020-08-25 19:09 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/91213806-6fd6d800-e712-11ea-9bb0-c6b03477bf8e.png)

Please, disable outline on-click when routing is disabled.

2020-08-27 10:15 UTC, xkureck requested changes
I am completely missing authorization on facility host detail page I think

2020-08-31 11:53 UTC, xkureck approved these changes

2020-09-01 09:12 UTC, xkureck approved these changes

2020-09-01 09:12 UTC, merged