Authorization - resource section
CESNET/perun-web-apps pull request #426
Opened 2020-08-25 18:14 UTC by xkostka2

* Authorization for resource section was added (except for managers page)
* Resolves #396

2020-08-26 11:41 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/91285540-a1d95000-e78d-11ea-957b-f0b54c3f5711.png)
Some bug occured that assigned services are accesible only from facility part, if vo-manager or resource-manager can get to this part of application the page should be accesible from vo part too.
![image](https://user-images.githubusercontent.com/32871167/91285854-faa8e880-e78d-11ea-8598-47ce46f4a931.png)
There should be some tooltip why the attributes cannot be checked(selected)
![image](https://user-images.githubusercontent.com/32871167/91286123-55dadb00-e78e-11ea-8cd9-fbd6d447dc28.png)
(tested as a group admin) Missing authorization to edit resource button.
![image](https://user-images.githubusercontent.com/32871167/91299342-bfb0b000-e7a1-11ea-9cdc-e305a17d80d3.png)
Missing authorization to link to the facility

2020-08-26 13:17 UTC, bodnara requested changes
![image](https://user-images.githubusercontent.com/23495969/91307145-dc52e500-e7ad-11ea-9721-8b3046e2108f.png)
As resource admin I get error when accessing Assigned services.
I believe this is caused by missing authorization for overview buttons as well as sidemenu items.
![image](https://user-images.githubusercontent.com/23495969/91307955-e75a4500-e7ae-11ea-8cf2-59482f99546e.png)
I would also suggest hiding checkbox column if there is no purpose for them

2020-08-31 14:27 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/91724415-932fd600-eb9d-11ea-813e-1ddc9947a5be.png)
Access to the services should only have perun admin.

2020-09-01 08:56 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/91827431-21a86400-ec3f-11ea-9595-61403fa965c5.png)
You rebased the adam PR that is merged but now there is two tooltips for checkbox in attributes. Please keep the Adams way of doing the tooltips.

2020-09-01 08:56 UTC, xkureck commented on apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
> +      })
We made some misscomunication, to get into the assigned services and see them/add/remove them should be done according to the policies.

2020-09-01 08:56 UTC, xkureck commented on apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.html
> +  [disableRouting]="!guiAuthResolver.isAuthorized('getServiceById_int_policy',[])"
This routing to the service detail should be enabled only for perun admins

2020-09-01 08:56 UTC, xkureck commented on apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
> +  <span  [matTooltipDisabled]="canRemoveGroups()" matTooltip="{{'RESOURCE_DETAIL.ASSIGNED_GROUPS.REMOVE_TOOLTIP' | translate}}">{{'RESOURCE_DETAIL.ASSIGNED_GROUPS.REMOVE_GROUP' | translate}}</span>
at least split this code into the - one "thing" one row, this is very hard to read

2020-09-01 08:56 UTC, xkureck commented on apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts
> +    if(this.guiAuthResolver.isPerunAdmin()){
also there we made a miscomunication

2020-09-01 08:56 UTC, xkureck commented on libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html
> +                (click)="readonly && showValue(keys[i], attribute.displayName)"
previous code: `(click)="readonly && attribute.displayName !== undefined && showValue(keys[i], attribute.displayName)"
` wasnt the attribute.displayName !== undefined important?

2020-09-01 14:07 UTC, xkureck approved these changes

2020-09-01 14:07 UTC, merged