Group Authorization
CESNET/perun-web-apps pull request #435
Opened 2020-08-31 15:40 UTC by xpavlic

Resolves #394
Authorization for group section added.

2020-09-01 15:15 UTC, xkureck requested changes
I guess attributes was made by Adam so when you rebase the attributes should work as it should?
![image](https://user-images.githubusercontent.com/32871167/91868268-d9a43400-ec74-11ea-842a-416b1139d319.png)
Because right now I cant see any tooltip why I can select the attributes
![image](https://user-images.githubusercontent.com/32871167/91868808-6ea72d00-ec75-11ea-8091-007a4cf0ea48.png)
As a vo observer I can see the checkboxes - that is really weird
![image](https://user-images.githubusercontent.com/32871167/91868981-a01ff880-ec75-11ea-86b8-65a0d565cf8e.png)
vo observer: I should see button create subgroup
![image](https://user-images.githubusercontent.com/32871167/91869216-e5dcc100-ec75-11ea-9d5b-d8e0d3e33ee1.png)
Shouldnt see that
![image](https://user-images.githubusercontent.com/32871167/91869318-0ad13400-ec76-11ea-809a-0ca9df5fdd00.png)
wrong tooltip when I want to click on checkbox and also I can click on create even if I dont have nothing checked, I know that it is not part of authorization but please fix that
![image](https://user-images.githubusercontent.com/32871167/91869613-656a9000-ec76-11ea-9061-ce6cd398fcfd.png)
Also please fix bug when I want to get into the detail of application of the group the sidemenu get crazy and it get me into the vo application, which is wrong, I want to stay in the group applications

2020-09-07 12:13 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/92360910-ddf5a480-f0ed-11ea-9d07-f636d6e805aa.png)
Hide the outline when the routing is disabled

2020-09-07 12:13 UTC, xkureck commented on libs/perun/components/src/lib/groups-list/groups-list.component.html
> +                                  [exporter]="exporter"></perun-web-apps-table-options>
one "thing" one row please

2020-09-07 12:13 UTC, xkureck commented on libs/perun/components/src/lib/groups-list/groups-list.component.html
> +             matSortDirection="asc" matSortDisableClear
one "thing" one row please

2020-09-07 12:13 UTC, xkureck commented on libs/perun/components/src/lib/groups-list/groups-list.component.html
> +               'SHARED_LIB.PERUN.COMPONENTS.GROUPS_LIST.ALREADY_MEMBER_TOOLTIP') | translate"
better code readability - translate in in the ts file and here you get only variables

2020-09-08 10:50 UTC, bodnara requested changes
Editing of email footer not working for any role
![image](https://user-images.githubusercontent.com/23495969/92466006-bb3bbc80-f1cf-11ea-9e17-434d0a9567bc.png)

Same goes for editing of notifications
![image](https://user-images.githubusercontent.com/23495969/92466165-fe962b00-f1cf-11ea-994b-68de1eef0d9b.png)

As Vo observer, I cannot open notification detail. I assume that this role should be able to see content of the notification only editing should be disabled.
![image](https://user-images.githubusercontent.com/23495969/92466492-77958280-f1d0-11ea-8684-ed138176cbe9.png)

After adding member the dialog is not closing. Perhaps you could fix it even if it is not part of authorization.
![image](https://user-images.githubusercontent.com/23495969/92466845-00142300-f1d1-11ea-9c8f-b4110c6f01ef.png)

As group-admin after creating subgroup I need to refresh page to gain authorization rights over this group.
Before refresh:
![image](https://user-images.githubusercontent.com/23495969/92467068-4f5a5380-f1d1-11ea-8870-1d55e865988f.png)
After refresh:
![image](https://user-images.githubusercontent.com/23495969/92467170-6c8f2200-f1d1-11ea-81df-23fdb6d1eb99.png)

As group admin I don't have rights to add/remove resources. I am not sure if this is expected behavior, maybe I am missing some information.
![image](https://user-images.githubusercontent.com/23495969/92467380-cbed3200-f1d1-11ea-9d71-3f7fb73b1d07.png)

2020-09-08 12:58 UTC, xpavlic commented
![image](https://user-images.githubusercontent.com/52922281/92478946-322e8080-f1e3-11ea-8274-6ee2e12e5f4d.png)
this is expected behaviour, because you also need RESOURCESELFSERVICE role.
![image](https://user-images.githubusercontent.com/52922281/92479165-76218580-f1e3-11ea-876c-7f2293113866.png)

2020-09-08 16:00 UTC, xkureck requested changes

2020-09-08 16:00 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts
>      }
```suggestion
      if (this.data.groupId) {
      this.groupsService.getGroupById(this.data.groupId).subscribe(group => {
        this.editAuth = this.authResolver.isAuthorized('group-addMail_ApplicationForm_ApplicationMail_policy', [group]);
        console.log('edit auth');
        console.log(this.editAuth);
      });
    } else if (this.data.voId) {
      const vo = {
        id: this.data.voId,
        beanName: "Vo"
      };
      this.editAuth = this.authResolver.isAuthorized('vo-addMail_ApplicationForm_ApplicationMail_policy', [vo]);
    }
```
This is suggestion for whole block starting from row 45. The method isAuthorized in this case need whole object group. It needs voId in the group object

2020-09-10 10:54 UTC, xkureck approved these changes

2020-09-10 11:03 UTC, merged