Copy form item privilege bug fix
CESNET/perun-web-apps pull request #481
Opened 2020-09-29 10:19 UTC by bodnara

Resolves #473 

* fixed bug when copy form items dialog would load Vos that user cannot access

2020-09-30 13:28 UTC, xkureck requested changes
I will ask you for some more things.
1. on application form comment button clear form - it is not working, ale we dont have use case for this button, its only for testing purpouses
2. I would like the same select field as it is on Vo for choosing groups
3. Also you didnt fix the bug that I wanted from you to fix. 
![image](https://user-images.githubusercontent.com/32871167/94691076-2bea7a80-0331-11eb-8a8c-e1f08c7bb1ea.png)
in best scenario we would like to inform the user if the application form(that he wants to copy) is empty. But the method that we call to be informed about that needs priviledges that user normally doesnt have. Find out if that information cant be get any other way and if not remove this check.

2020-10-07 15:53 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/95353359-79cc2900-08c3-11eb-90e0-3705bd8ea244.png)

There are still displayed VOs where the user doesn't have permission to copy Application form.

![image](https://user-images.githubusercontent.com/47856862/95354064-4a69ec00-08c4-11eb-9c84-d8713e031841.png)

When I selected group and then changed VO, it still made a request for group-to-vo instead of vo-to-vo

![image](https://user-images.githubusercontent.com/47856862/95354923-47233000-08c5-11eb-98b6-636500b094f9.png)

This is just a minor cosmetic issue. I don't see the point of copying the Application form of the same entity into itself (whether it is Vo or group)

2020-10-08 10:41 UTC, bodnara commented
> There are still displayed VOs where the user doesn't have permission to copy Application form.

VOs are displayed correctly because you need to select VO in order to select Group from which you can copy. The problem is that you cannot copy from the VO itself. After some consultation with @xkureck, we decided that upon some incorrect combination of VO and Group notification will pop to explain to user what happened.

2020-10-08 11:21 UTC, xkostka2 approved these changes

2020-10-12 17:09 UTC, xkureck approved these changes

2020-10-12 17:09 UTC, merged