App alert reworked
CESNET/perun-web-apps pull request #500
Opened 2020-10-05 23:04 UTC by xpavlic

Resolves #461 

- created Alert component showing bold text in the middle of page

- created Info component showing info message as used to, but without blue background

- old alert component renamed to Error component 

- usage of old alert component updated

2020-10-22 15:42 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/96896249-95236080-148d-11eb-86f6-d873d37827b5.png)
The style of  when table is empty/no items are filtered should be like this alert, that means some icon - dont have to be like this one, frame around the text and the text is on left side

2020-10-30 15:59 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/97722240-b78b2e80-1aca-11eb-8d30-2d7594b5bcf6.png)
forget to use the component here
ok, originally I thought that app-info is for this
![image](https://user-images.githubusercontent.com/32871167/97727383-9fb6a900-1ad0-11eb-9117-ac5693461aea.png)
and for error it is component app-alert
but it is vice versa, that is really weird, I would expect for some error app-alert component and for some info app-info component
also I made a mistake, when I thought it must be another component, it can be just 1 component it can be named app-alert but, in the specification you shouldnt specify color, but the component should take some input where we would specify it it is used for warn or info, and in the component itself there could be *ngIf that would specify which look to use


and also 
![image](https://user-images.githubusercontent.com/32871167/97726131-34b8a280-1acf-11eb-98e0-84b4ca516a5e.png)
This should be app-alert not info

2020-11-01 20:42 UTC, xpavlic commented
![image](https://user-images.githubusercontent.com/52922281/97814881-aab53900-1c8a-11eb-9f8d-4985434777b7.png)
this is warn alert not info alert (info allert doesn't have image)

2020-11-11 17:38 UTC, xkureck approved these changes

2020-11-11 17:38 UTC, merged