User session expiration
CESNET/perun-web-apps pull request #560
Opened 2020-11-17 13:50 UTC by bodnara

Resolves #404 

* when session expires, dialog will pop-up to notify user about this event and asks him to sign in

2020-11-17 18:17 UTC, xkureck commented
Circular dependency between "perun-dialogs" and "perun-services" detected: perun-dialogs -> perun-services -> perun-dialogs

2020-11-18 11:17 UTC, Vojtech-Sassmann requested changes

2020-11-18 11:17 UTC, Vojtech-Sassmann commented on libs/perun/services/src/lib/auth.service.ts
> +import { SessionExpirationDialogComponent } from '../../../dialogs/src/lib/session-expiration-dialog/session-expiration-dialog.component';
All imports should start with `@perun-web-apps`

2020-11-19 08:02 UTC, Vojtech-Sassmann commented
Hi @bodnara, could you please show this dialog also in ApiInterceptor? You can replace the UserNotLogedIn error.

2020-11-19 12:43 UTC, Vojtech-Sassmann approved these changes

2020-11-19 14:13 UTC, xkureck approved these changes

2020-11-19 14:13 UTC, merged