Add new roles to Managers
CESNET/perun-web-apps pull request #568
Opened 2020-11-25 12:26 UTC by HejdaJakub

* Roles are now fetching through api method getAllRolesManagementRules and they are also assigned to Vo/Group/Facility/Resource via method attribute named primaryObject.

2020-11-26 14:07 UTC, bodnara approved these changes
Everything seems to be working correctly. However I would like to ask @xkureck for review just to make sure I didn't miss anything.

2020-11-26 15:18 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/100367396-73744680-3002-11eb-9eda-f0764365a01b.png)
I got one problem with the order of the items in the select role selector. In the facility/group/resource managers page its actually ok, and I like that order, but in the vo-managers page the order of the items its not the way I would like. I would like as the first default item vo manager for sure, definitely not Sponsor. The order of the items here should be something like - vo manager, vo observer, sponsor, top group creator, trusted facility admin. Its because of UX, when user initially come here to this page he would automatically see Sponsors, but this role is on some our instances not used at all.

2020-11-30 10:26 UTC, HejdaJakub commented
> ![image](https://user-images.githubusercontent.com/32871167/100367396-73744680-3002-11eb-9eda-f0764365a01b.png)
> I got one problem with the order of the items in the select role selector. In the facility/group/resource managers page its actually ok, and I like that order, but in the vo-managers page the order of the items its not the way I would like. I would like as the first default item vo manager for sure, definitely not Sponsor. The order of the items here should be something like - vo manager, vo observer, sponsor, top group creator, trusted facility admin. Its because of UX, when user initially come here to this page he would automatically see Sponsors, but this role is on some our instances not used at all.

The order has been edited. If some new role will be added in the future, the Vo Admin will be always at first position and the Vo Observer will be always at second position, but the rest of roles will be ordered by alphabet. Is it ok?

2020-12-01 18:09 UTC, xkureck approved these changes

2020-12-01 18:09 UTC, merged