Managers page authorisation
CESNET/perun-web-apps pull request #574
Opened 2020-12-04 13:04 UTC by bodnara

Related task: # 6813

* added authorisation in managers page for:
* selected roles and their 'mode' based on Perun rules
* add/remove buttons
* missing sidemenu and overview authorisation

2020-12-08 10:59 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/101468570-e4412a00-3943-11eb-9f06-d99be3f9561b.png)
Please add authorization to resource overview(advanced settings)
i got roles resource admin + resource-self service(and didnt saw anything in resource-settings-overview), then I figured it out that just the role resource admin cannot see it
![image](https://user-images.githubusercontent.com/32871167/101472071-5f0c4400-3948-11eb-97ac-5c99b8c258be.png)


resource-self service shouldnt see the managers page at all because it doesnt have the rights to call the method
![image](https://user-images.githubusercontent.com/32871167/101472970-8e6f8080-3949-11eb-9c9d-4747c4bb95ab.png

2020-12-15 10:23 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/102197298-3db7d480-3ec1-11eb-8b24-fcc105547a07.png)
I have resource observer role - i can see in the resource overview advanced settings and then managers as I should but i cant see that in sidemenu which is bug
Wait I just realized that I cant see the advanced settings in the resource section in sidemenu even if I am perun admin
Also please look on the group advaced settings - both sidemenu and overview when you are only member of that group 
![image](https://user-images.githubusercontent.com/32871167/102198613-e31f7800-3ec2-11eb-9709-ec3b75eb0afd.png)

2020-12-15 12:01 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/102198918-414c5b00-3ec3-11eb-99ed-99213d86dd30.png)

With role trusted facility admin I get a privileged exception when clicking on advanced settings.

2020-12-15 12:23 UTC, bodnara commented
With only role trusted facility admin you shouldn't see advanced settings.

![image](https://user-images.githubusercontent.com/23495969/102214290-54b5f100-3ed8-11eb-963a-2498a3a96ccf.png)

I recently pushed a new version so try to update and see if the issue persists.

2020-12-15 12:47 UTC, xkostka2 approved these changes

2020-12-15 14:22 UTC, xkureck requested changes

2020-12-15 14:22 UTC, xkureck commented on apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
> +            activatedRegex: `${regexStart}\\d+/resources/\\d+/settings/managers$`
```suggestion
            activatedRegex: `${regexStart}/\\d+/resources/\\d+/settings/managers$`
```

2020-12-15 14:41 UTC, merged