Sort and filter changes
CESNET/perun-web-apps pull request #607
Opened 2021-02-04 14:02 UTC by xkostka2

* Listed changes applies to all list components
* Adjusted sort algorithm to sort czech characters properly
* Filter now checks only visible columns while
* Filter works case insensitive
* Latest OpenAPI changes were applied

2021-02-05 08:59 UTC, xkureck requested changes
please sort TS lint problems 
`/home/xkureck/perun-web-apps/libs/perun/utils/src/lib/perun-utils.ts:649:28
ERROR: 649:28  triple-equals  == should be ===
ERROR: 653:9   prefer-const   Identifier 'dataStrA' is never reassigned; use 'const' instead of 'let'.
ERROR: 654:9   prefer-const   Identifier 'dataStrB' is never reassigned; use 'const' instead of 'let'.
ERROR: 656:62  triple-equals  == should be ===

Lint errors found in the listed files.
`

2021-02-05 08:59 UTC, xkureck commented on libs/perun/components/src/lib/members-list/members-list.component.ts
> +      };
![image](https://user-images.githubusercontent.com/32871167/107011027-65c40580-6797-11eb-989f-b252ea99044a.png)
this is the desired sorting in member-list when it comes to sorting according to names
primarily we want to sort according to what is in the "lastName" if last name is null then sort according to "firstName" if first name is null then sort according to something else so the method at least doesnt throw error

2021-02-05 08:59 UTC, xkureck commented on libs/perun/components/src/lib/members-list/members-list.component.ts
> +      };
![image](https://user-images.githubusercontent.com/32871167/107011294-bdfb0780-6797-11eb-839a-ca777c261daf.png)
this is your sorting according to full name, you are even counting the titles..

2021-02-05 08:59 UTC, xkureck commented on libs/perun/components/src/lib/members-list/members-list.component.ts
> +      };
same problem is everywhere where is fullName of user sorted - application-list, candidate-list

2021-02-05 10:48 UTC, mvocu reviewed
Looks good to me (as far as I can tell), but contains unnecessary white-space changes and changes probably not related to the main purpose.

2021-02-05 10:48 UTC, mvocu commented on libs/perun/openapi/src/lib/api/servicesManager.service.ts
> +    public deleteService(service: number, force?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
How is this related to the pull request objective?

2021-02-05 10:48 UTC, mvocu commented on libs/perun/openapi/src/lib/api/usersManager.service.ts
> +     * @param addUserExtSourceInput
Please do not commit empty space changes.

2021-02-05 12:30 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/107021716-cb6abe80-67a4-11eb-9cc0-b36c15c485b8.png)
with this changes you break the functionality of "sorting according to recently viewed" 
the default sorting is set to column 'recent' in some tables(group, resource, facility, vo) so that the recent items are on top of the table - user have easy access to them

I guess that you can completely remove the
`this.dataSource.sortingDataAccessor = (item, property) => {`
method, because you are overriding the behaviour in the method sortData
I suggest to use the sortData function and then use the sortingDataAccessor to take into consideration the unusualness of each table

Also I think you should change the filter method - when you are adding one string to another like id + name + description the filter could find something that we dont want
![image](https://user-images.githubusercontent.com/32871167/107033948-50aa9f00-67b6-11eb-8f43-275dfe60ce99.png)

2021-02-05 12:30 UTC, xkureck commented on apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.ts
> +          parseFullName(data.user) : data.createdBy.slice(data.createdBy.lastIndexOf('=')+1, data.createdBy.length);
here we would also like to sort by the last name, if we got object User

2021-02-05 12:30 UTC, xkureck commented on libs/perun/components/src/lib/services-status-list/services-status-list.component.ts
> +      };
when sorting by ID - its not working - no error appears but it doesnt do anything
when sorting by end and start date the error in console aapears
![image](https://user-images.githubusercontent.com/32871167/107033579-ce21df80-67b5-11eb-80a7-a4e3c5d8680e.png)

2021-02-15 16:30 UTC, xkureck requested changes

2021-02-15 16:30 UTC, xkureck commented on libs/perun/components/src/lib/resources-list/resources-list.component.ts
> +        return data[column];
```suggestion
        return data['name'];
```

2021-02-15 16:30 UTC, xkureck commented on libs/perun/components/src/lib/groups-list/groups-list.component.ts
> +        return data[column];
```suggestion
        return data['name'];
```

2021-02-15 16:30 UTC, xkureck commented on libs/perun/components/src/lib/facility-select-table/facility-select-table.component.ts
> +        return data[column];
```suggestion
        return data['name'];
```

2021-02-16 12:08 UTC, merged