Block/Allow service on destination
CESNET/perun-web-apps pull request #624
Opened 2021-03-01 10:54 UTC by bodnara

* added buttons for blocking/allowing service on destination to facility detail - service destination page

2021-03-01 12:35 UTC, Vojtech-Sassmann requested changes

2021-03-01 12:35 UTC, Vojtech-Sassmann commented on apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.html
> +    color="accent"
I don't really like the style of these buttons. You should usually have only one action and one danger button at most. This really makes it look weird. I would just use a neutral color for these two buttons.

2021-03-02 11:25 UTC, xkureck reviewed
I agree with Vojta
and second thing if all things that are selected are allowed, the button "Allow" make disabled, if all thing that are selected are blocked, the button "Block" should be disabled, if the things that are selected are mixed make the both buttons non disabled
![image](https://user-images.githubusercontent.com/32871167/109641743-59428b00-7b52-11eb-9ae5-9286e34ae495.png)
my idea how the buttons could look

2021-03-03 13:14 UTC, xkureck reviewed
In my opinion the "flat" buttons looks really weird when they doesnt have any colour

2021-03-03 13:14 UTC, xkureck commented on apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.html
> +    mat-flat-button
```suggestion
    mat-stroked-button
```

2021-03-03 13:14 UTC, xkureck commented on apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.html
> +    mat-flat-button
```suggestion
    mat-stroked-button
```

2021-03-05 10:23 UTC, xkureck approved these changes

2021-03-05 10:23 UTC, merged