ExtSource management added to group section
CESNET/perun-web-apps pull request #635
Opened 2021-03-10 13:10 UTC by HejdaJakub

* ExtSource page was added to group section.
* I also fixed the add ExtSource dialog in VO section, where was not shown correct data.

2021-03-11 10:42 UTC, bodnara requested changes
Overall it is well done. However, there are some changes needed before merging. 
Please add ext. sources page to the side-menu in group section.
I assume you followed the structure of ext. sources page in organizations section which is great. Unfortunately this page along side with the add ext. source dialog had some issues on their own.  
First of all it is missing the remove dialog completely. Take a look at some other page on how the remove dialog looks like and create one that will be used for both organizations and groups. It should be fairly straight forward.
Secondly it makes asynchronous calls in a for loop which I believe should be replaced with a recursive function (take a look how it is done on service destination page with allowing/blocking). But honestly none of those two are perfect and it can maybe stay the way it is now.
Last thing I would recommend is instead of creating a new add dialog for groups, just make some changes in the existing one to support both options. These dialogs are mostly identical and it leads to code duplication which we obviously try to avoid. (you can take inspiration from add member dialog for this)

2021-03-12 11:17 UTC, HejdaJakub commented
> Overall it is well done. However, there are some changes needed before merging.

- External sources was added to the side menu.
- Remove dialog was created and added to both sections.
- Async function call in for loop was replaced by recursoin.
- I modified the old add dialog and now both sections are using the same dialog.

2021-03-12 12:08 UTC, bodnara requested changes
It is looking good. There are only a couple of really small issues.

2021-03-12 12:08 UTC, bodnara commented on apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
> +      settingsChildrenLinks.push({
Use the same policy as in the overview.

2021-03-12 12:08 UTC, bodnara commented on apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-extsources/group-settings-extsources.component.ts
> +      theme: 'vo-theme'
'group-theme'

2021-03-12 12:08 UTC, bodnara commented on apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-extsources/group-settings-extsources.component.ts
> +      theme: 'vo-theme'
'group-theme'

2021-03-12 17:42 UTC, HejdaJakub commented on apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
> +      settingsChildrenLinks.push({
Policy fixed.

2021-03-12 17:43 UTC, HejdaJakub commented on apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-extsources/group-settings-extsources.component.ts
> +      theme: 'vo-theme'
Done.

2021-03-12 17:43 UTC, HejdaJakub commented on apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-extsources/group-settings-extsources.component.ts
> +      theme: 'vo-theme'
Done.

2021-03-16 13:06 UTC, bodnara approved these changes

2021-03-17 08:40 UTC, merged