Set different sponsor when creating sponsored member
CESNET/perun-web-apps pull request #636
Opened 2021-03-10 13:36 UTC by bodnara

* added option to choose different sponsor when user is authorized to do so
* implemented stepper to "create sponsored member" dialog

2021-03-11 13:35 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/110788786-5d1b8f00-826f-11eb-98bf-1bf0b7f5d222.png)

Disable button when the user is not selected, this happens for example when Vo has no sponsors.

![image](https://user-images.githubusercontent.com/47856862/110788971-9c49e000-826f-11eb-9c3b-97b12e45ba39.png)

Even tho I am Perun admin, it does not show me on the list of potential sponsors.

2021-03-15 08:51 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/111125782-47a9ac00-8572-11eb-918e-104de57adcbf.png)

After displaying the dialog this error pops out. Although, this error won't pop up in production, according to best practices it shouldn't be there. Try to get rid of it if possible.

![image](https://user-images.githubusercontent.com/47856862/111125308-c5b98300-8571-11eb-81ac-03633e0d82f8.png)

I suggest moving text in the alert into the tooltip of Create button which will be disabled if there are no sponsors.

2021-03-17 12:16 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/111462235-7b293980-871e-11eb-898b-2e08456fd6f3.png)
Actually between all the section insert some gaps please

![image](https://user-images.githubusercontent.com/32871167/111464488-1f13e480-8721-11eb-91b1-d1a6b114e2dd.png)
In that try I was sponsor + vo observer so I could find for other sponsor in the organization so I have choosen somebody else and it throw at me priviledge exception
Please make visible the select box to only the users that have the priviledge to make somebody else sponsor

Another problem for me with the ux is that If I want to make me the sponsor then I dont really know what to do on this page
![image](https://user-images.githubusercontent.com/32871167/111465073-efb1a780-8721-11eb-942e-1c121f964afe.png)
Why is jana Prepechalova set as a sponsor as default(why is first on list set as default sponsor) then if I want to make myself as sponsor I need to find me on the list. I think that the default option should be me(the user). Another solution could be that we could solve this by radio buttons where default chosen option would be "make myself sponsor" and the other would be the select field with selecting somebody else the sponsor.

2021-03-17 12:16 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
> +      if (this.findSponsorsAuth) {
if this.findSponsorsAuth is false then dont show at all the select field for making somebody else sponsor

2021-03-18 11:08 UTC, Vojtech-Sassmann approved these changes

2021-03-18 11:44 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/111620371-e8a09d00-87e6-11eb-89bb-b639818397be.png)
Hi there is still problem with authorization. On this account I have role Sponsor + vo admin and I have choosen as sponsor somebody else. Which I cant do.
According to the policy
`createSponsoredMember_Vo_String_Map<String_String>_String_User_LocalDate_policy:
    policy_roles:
      - SPONSOR: Vo
        SELF: User
    include_policies:
      - default_policy`
I must have the role sponsor and the sposor must be me or I must be perun admin. Please show only the selection of sponsor only to those who have right to make somebody else sponsor. Or even better make the option "select other sponsor from this organization" disabled with tooltip that says the user dont have the priviledge to make somebody else sponsor.

2021-03-18 12:33 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/111625982-c2323000-87ed-11eb-97fe-addb99b00f94.png)

Check one of the radio buttons by default so this does not happen.

![image](https://user-images.githubusercontent.com/47856862/111626174-fc033680-87ed-11eb-8f57-3872c0528e15.png)

I selected a sponsor, then selected myself and then checked to select another sponsor. Clear the value or display it. 

![image](https://user-images.githubusercontent.com/47856862/111625524-37513580-87ed-11eb-9a2f-61a0aa21f03b.png)

Just a minor suggestion. Mark fields Login and Password as required.

2021-03-18 13:01 UTC, bodnara commented
> Just a minor suggestion. Mark fields Login and Password as required.

These fields can be disabled, optional or reqiured depending on the configuration and selected namespace.

2021-03-18 13:56 UTC, xkostka2 approved these changes

2021-03-18 14:19 UTC, xkureck approved these changes

2021-03-18 14:19 UTC, merged