Vo overview statistics
CESNET/perun-web-apps pull request #637
Opened 2021-03-11 12:47 UTC by bodnara

* added table with members count per status to vo overview

2021-03-12 08:18 UTC, HejdaJakub reviewed
Implementation looks good, so I have only one comment. We will want to implement similar statistics also in group section further and maybe on a separate page, so I recommend to create new reusable component for this statistics.

2021-03-15 08:00 UTC, HejdaJakub approved these changes

2021-03-17 09:42 UTC, Vojtech-Sassmann commented
Hi @bodnara, if there are no more changes requested, please rebase this PR. You can even merge it and update the issue status in Redmine (move it to resolved and write changelog to wiki)

2021-03-17 12:22 UTC, xkureck commented on apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.html
> +  </app-statistics-card>
I suggest moving the statisticts under the perun-web-apps-menu-buttons-field
I dont think that the statistics are that important so they are at the top, the box button are more important in my opinion

2021-03-18 10:10 UTC, Vojtech-Sassmann requested changes
Please, align the card with the rest of the content. You can do it just by setting the left margin to 0.

2021-03-18 11:10 UTC, Vojtech-Sassmann approved these changes

2021-03-18 11:11 UTC, merged