publications authors + author details page implementeda
CESNET/perun-web-apps pull request #642
Opened 2021-03-16 15:45 UTC by xkureck

* added table for authors
* added page for authors
* added table for publications
* added page for author detail
* added remove publication dialog
* added show cite dialog
* added filter publication component

2021-03-16 15:46 UTC, xkureck commented
before reviewing you need to 'npm install' i added new library

2021-03-17 09:24 UTC, Vojtech-Sassmann requested changes

2021-03-17 09:24 UTC, Vojtech-Sassmann commented on apps/publications/src/app/components/publication-filter/publication-filter.component.html
> +    <mat-icon>search_off</mat-icon>
I would just suggest adding here some text or a tooltip on what this button does.

2021-03-17 12:50 UTC, Vojtech-Sassmann approved these changes

2021-03-17 16:02 UTC, merged