Added Facilities section to User detail
CESNET/perun-web-apps pull request #652
Opened 2021-03-24 12:07 UTC by HejdaJakub

* In perun admin User detail is now Facilities section.
* Facilities can filtered by id, name or description.

2021-03-24 14:02 UTC, bodnara requested changes
It looks good. There is one small fix needed regarding when "loading" is active.

2021-03-25 11:14 UTC, HejdaJakub commented on apps/admin-gui/src/app/users/pages/user-detail-page/user-facilities/user-facilities.component.ts
> +  ngOnInit(): void {
Added.

2021-03-25 11:14 UTC, HejdaJakub commented on apps/admin-gui/src/app/users/pages/user-detail-page/user-facilities/user-facilities.component.ts
> +  refreshTable() {
Added.

2021-03-25 11:16 UTC, HejdaJakub commented on apps/admin-gui/src/app/users/pages/user-detail-page/user-facilities/user-facilities.component.ts
> +    this.refreshTable();
Refresh has been moved.

2021-03-25 11:34 UTC, bodnara approved these changes

2021-03-31 07:11 UTC, merged