Replacing mat-table-exporter library
CESNET/perun-web-apps pull request #664
Opened 2021-04-01 11:39 UTC by xkostka2

* Library mat-table-exporter, used to exporting displayed data from tables, was replaced by custom implementation in all tables
* Supported export formats have been reduced to CSV, however, everything is ready in case new formats were to be added

2021-04-07 14:05 UTC, xkureck requested changes
1. export of attributes table
![image](https://user-images.githubusercontent.com/32871167/113868523-0c388100-97b0-11eb-98f7-633e50d6067b.png)
As you can see in the picture its not nice if you are trying to export some attributes. The question is if there is use-case for exporting attributes and if it is in how form we want to export it.
same problem in resources table 
![image](https://user-images.githubusercontent.com/32871167/113879598-f67c8900-97ba-11eb-9990-06539d934cb4.png)


Checked tables:
attr-def-list.component.html 
blacklist-list.component.html 
destination-list.component.html 
generate-sponsored-members-dialog.component.html 
ext-sources-list.component.html 
facilities-list.component.html 
hosts-list.component.html 
members-candidates-list.component.html 
owners-list.component.html 
resources-tags-list.component.html 
security-teams-list.component.html 
services-list.component.html 
members-list.component.html 
sponsored-members-list.component.html 
users-list.component.html 
application-list-details.component.html 
applications-list.component.html 
attributes-list.component.html 
facility-select-table.component.html 
groups-list.component.html 
resources-list.component.html 

for the rest of the tables I would like to ask @HejdaJakub to give his review

2021-04-09 09:47 UTC, HejdaJakub requested changes

2021-04-09 09:47 UTC, HejdaJakub commented on apps/publications/src/app/components/authors-list/authors-list.component.html
> +    <perun-web-apps-table-options (exportData)="exportData($event)"></perun-web-apps-table-options>
Authors are exported without titles.
![image](https://user-images.githubusercontent.com/70371638/114157273-c3093e00-9923-11eb-8a6b-6108e5cfe3cf.png)

2021-04-09 09:47 UTC, HejdaJakub commented on apps/publications/src/app/components/publications-list/publications-list.component.html
> +    <perun-web-apps-table-options (exportData)="exportData($event)"
Columns `Reported by` and `Thanks` should be represented by names, but in exported CSV are only counts.
![image](https://user-images.githubusercontent.com/70371638/114158619-2f387180-9925-11eb-92fe-d799591193d2.png)

2021-04-09 09:47 UTC, HejdaJakub commented on apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html
> +        <table [dataSource]="dataSource" class="w-100" mat-table>
You only removed old matTbaleExporter and you didn't replace it by new solution. If it was your purpose, then just ignore this comment.

2021-04-13 15:53 UTC, xkureck approved these changes
You have my approve for core functionality + tables that I have reviewed

2021-04-13 19:39 UTC, HejdaJakub requested changes
All exported tables look good, but there is one last issue. A few days ago was merged branch with changes in Publication list (#657) and there is the thanks-list component, which uses an old exporter. But you deleted MatTableExporter, so my IDE throws an error and this component should be changed too.
![Error](https://user-images.githubusercontent.com/70371638/114610722-867d6f80-9ca0-11eb-90d9-0ecabadbd28b.png)

2021-04-14 10:11 UTC, HejdaJakub approved these changes

2021-04-14 10:12 UTC, merged