Delete Vo dialog
CESNET/perun-web-apps pull request #666
Opened 2021-04-08 09:45 UTC by bodnara

* created new dialog for deleting entities so far only Vo is implemented
* added option to delete Vo on its detail
* replaced existing remove dialog

2021-04-08 12:09 UTC, xkostka2 requested changes
![image](https://user-images.githubusercontent.com/47856862/114022345-f4293600-9871-11eb-9a91-3cc2716e9fdb.png)

Just a minor issue, the first letter should be capital

2021-04-12 09:45 UTC, bodnara commented on apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts
> +      }
It was decided that routing to home page should be sufficient

2021-04-12 12:57 UTC, xkostka2 approved these changes

2021-04-13 15:30 UTC, xkureck approved these changes

2021-04-13 15:30 UTC, merged