Group checkbox
CESNET/perun-web-apps pull request #680
Opened 2021-04-21 14:01 UTC by xkureck

* added new application for item type - you can set it and edit it
* you can manage set of groups which will be presented to the user in vo application

please check also my broken english and the the labels in general

2021-04-21 17:00 UTC, Vojtech-Sassmann reviewed
I think this should work pretty well, I have just one comment. I also like the refactorization.

2021-04-22 09:36 UTC, xkureck commented on apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.ts
> +      this.removeAuth = this.authResolver.isAuthorized('deleteGroupsFromAutoRegistration_List<Group>_policy', [vo, this.groups[0]]);
we already have implemented some logic for that, I just forgot its here, now its repaired

2021-04-27 09:03 UTC, Vojtech-Sassmann requested changes
I think this works well. Just it might be worth to adjust some of the texts.

2021-04-27 11:16 UTC, xkureck commented on apps/admin-gui/src/assets/i18n/en.json
> +          "HELP": "On this page, you can set up a set of groups that will be displayed to users on an application to the organization. The user can select any set of these groups and by that make a n
thanks for helping me with the labels

2021-04-27 13:27 UTC, Vojtech-Sassmann approved these changes

2021-04-27 13:28 UTC, merged