Login screen
CESNET/perun-web-apps pull request #690
Opened 2021-05-06 12:30 UTC by Vojtech-Sassmann

* Implemented login screen for the AdminGui. This login screen is shown
when user is not logged in and the config property `auto_auth_redirect`
is set to false.
* Login screen also added to the user profile, HOWEVER! it is not
finished. The app component has to be adjusted so the sidemenu is
hidden.

2021-05-11 13:18 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/117820047-72f70180-b26a-11eb-9063-6d8ef31815d8.png)
Some sort of text would be nice above the login button. Also consider using the "sign in" label on the button
![image](https://user-images.githubusercontent.com/32871167/117821398-d3d30980-b26b-11eb-84d4-32f1aebd76f4.png)
FIx lint

2021-05-11 14:58 UTC, Vojtech-Sassmann commented on apps/admin-gui/src/app/app.component.html
> +<ng-template [ngIf]="!isLoginScreenShow">
Hi @xkureck, I have refactored the login screen. Now it should be easier to add it to other apps.

2021-05-12 09:53 UTC, xkureck commented on libs/perun/login/src/lib/login-screen/login-screen.component.html
> +        Login
localization

2021-05-12 09:53 UTC, xkureck reviewed
![image](https://user-images.githubusercontent.com/32871167/117955648-8c568700-b318-11eb-98e6-ca80c111586c.png)
Did you considered this or do you think we just dont need it?

2021-05-12 10:07 UTC, Vojtech-Sassmann commented
> ![image](https://user-images.githubusercontent.com/32871167/117955648-8c568700-b318-11eb-98e6-ca80c111586c.png)
> Did you considered this or do you think we just dont need it?

Sorry, I didn't notice the comment. I will add the text and also change the label.

2021-05-13 07:50 UTC, xkureck approved these changes

2021-05-13 07:51 UTC, merged