feat(profile): added login screen
CESNET/perun-web-apps pull request #703
Opened 2021-05-13 16:30 UTC by Vojtech-Sassmann

* Added support for login screen to the user profile.

2021-05-13 16:32 UTC, Vojtech-Sassmann commented
Unfortunately, I didn't manage to use the shared base layout component, because the profile is using its custom footer and the base layout is a bit different than in the other applications. In the future, it would be good to unify the footer and use one footer for all of our apps.

2021-05-13 19:46 UTC, xkureck requested changes

2021-05-13 19:46 UTC, xkureck commented on apps/user-profile/src/app/components/profile-login-screen-base/profile-login-screen-base.component.html
> +    <perun-web-apps-breadcrumbs></perun-web-apps-breadcrumbs>
I dont think it needs to be here

2021-05-13 19:46 UTC, xkureck commented on apps/user-profile/src/app/components/profile-login-screen-base/profile-login-screen-base.component.html
> +  <perun-web-apps-header [hideToggle]="true"></perun-web-apps-header>
The logo in this component is clickable

2021-05-14 07:59 UTC, Vojtech-Sassmann commented on apps/user-profile/src/app/components/profile-login-screen-base/profile-login-screen-base.component.html
> +    <perun-web-apps-breadcrumbs></perun-web-apps-breadcrumbs>
You are right, I have removed it.

2021-05-14 07:59 UTC, Vojtech-Sassmann commented on apps/user-profile/src/app/components/profile-login-screen-base/profile-login-screen-base.component.html
> +  <perun-web-apps-header [hideToggle]="true"></perun-web-apps-header>
Fixed.

2021-05-14 08:24 UTC, xkureck approved these changes

2021-05-14 08:24 UTC, merged