Assigned Group/Resource status
CESNET/perun-web-apps pull request #727
Opened 2021-06-09 07:32 UTC by bodnara

* added column with status to group and resource table
* changed group table hideColumn input to displayColumn

2021-06-09 07:35 UTC, bodnara commented
This draft must be merged after this one: https://github.com/CESNET/perun/pull/3244

2021-06-11 07:18 UTC, xkureck commented
![image](https://user-images.githubusercontent.com/32871167/121646608-cb056b80-ca95-11eb-81d3-71aa263d8f40.png)

After discussing with @Vojtech-Sassmann This problem cant be resolved in this sprint and thus this PR won be merged this sprint. Next sprint we will plan the fix.

2021-06-11 11:57 UTC, xkureck commented
+ some sort of icons could be nice for the status of the group on resource/status of the resource of group

2021-06-17 09:00 UTC, xkureck requested changes

2021-06-17 13:04 UTC, xkureck approved these changes

2021-06-17 13:04 UTC, merged