feat(admin): change status of group-resource assigment
CESNET/perun-web-apps pull request #788
Opened 2021-07-26 13:59 UTC by bodnara

* group-resource assignment can be activated or deactivated from both group and resource lists

2021-07-27 12:50 UTC, HejdaJakub requested changes
The code seems to be ok, I have only one thing. If I want to change status from `INACTIVE` to `ACTIVE`, there is no default sync/async option selected and the submit button is not disabled, so I can submit the dialog without any selected option. I would prefer to choose one of them as the default selected option.
![image](https://user-images.githubusercontent.com/70371638/127155858-73810e16-dbaf-456e-bd19-5079eb83f9a3.png)

2021-07-27 13:31 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/127131523-25234a55-5d54-44a4-aedb-2fb498e16734.png)
I want some description of what would happen if I change the status

![image](https://user-images.githubusercontent.com/32871167/127133658-78a79d25-5e20-4c71-9e8d-eb9b3b22abe6.png)
Nothing is selected but I can still submit the dialog, if something would be preselected that would be great. 
![image](https://user-images.githubusercontent.com/32871167/127133966-8ead5910-1621-4bc3-9a5c-7f4bc80acb50.png)
The description of what is asynchronous/synchronous assigment is great but I still dont have any idea what that means.

2021-07-28 09:54 UTC, HejdaJakub reviewed
Loading spinner would look better in the middle of the dialog.
![image](https://user-images.githubusercontent.com/70371638/127302522-82daa88d-aaec-424c-b919-fa32290afd25.png)

2021-07-29 14:59 UTC, xkureck requested changes

2021-07-29 14:59 UTC, xkureck commented on libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html
> +  <h5 class="mb-2">
```suggestion
  <p class="mb-4">
```

2021-07-29 15:00 UTC, xkureck commented
> Loading spinner would look better in the middle of the dialog.
> ![image](https://user-images.githubusercontent.com/70371638/127302522-82daa88d-aaec-424c-b919-fa32290afd25.png)

agree with jakub, also some appropriate colour would be nice

2021-08-02 13:40 UTC, xkureck approved these changes
just repair this little code readibility upgrades and then merge it

2021-08-02 13:40 UTC, xkureck commented on libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.ts
> +    if(this.status==="ACTIVE"){
```suggestion
    if(this.status === "ACTIVE") {
```

2021-08-02 13:40 UTC, xkureck commented on libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html
> +<div class="{{theme}}">
please check the format of this html, add spaces where it should be, remove them where they shouldnt be

2021-08-04 06:59 UTC, HejdaJakub approved these changes

2021-08-04 10:55 UTC, merged