feat(perun-web-apps): add support for creating service members
CESNET/perun-web-apps pull request #793
Opened 2021-07-29 12:39 UTC by xkostka2

* Added page into VO detail, where we can view all the service members in current VO and also create new ones
* Added dialog for creating service members
* Actual OpenAPI has been generated

2021-07-29 12:43 UTC, Vojtech-Sassmann commented
@xkostka2 Again, don't use the `perun-web-apps` scope, see: https://github.com/CESNET/perun-web-apps/pull/792#pullrequestreview-717769187

2021-07-29 16:33 UTC, xkureck requested changes
i am missing remove button(for removing the service member from VO) - you can use for that universal remove dialog I think
I think that also michal wanted it on the basic overview not on the advanced settings
![image](https://user-images.githubusercontent.com/32871167/127523746-daa60202-c31d-4e4f-8c64-dbd9f62b6c81.png)
I think that we have in our library some image called service_identity_<color> - that would be probably better than icon for group

![image](https://user-images.githubusercontent.com/32871167/127525490-12fd4f42-4913-400e-9d7f-1204a774dc64.png)
When I change the namespace some warning appears

![image](https://user-images.githubusercontent.com/32871167/127525818-a339221c-2abb-4558-8595-c9ba419e03f3.png)
When I change the namespace back to not selected some error appears, which is weird.

![image](https://user-images.githubusercontent.com/32871167/127526135-a7931033-19e0-4caa-8b96-4d1dc166ab3f.png)
The position of the buttons "next" "create" and "cancel"  is super weird. please inspire in our "create sponsored member" dialogs. Btw when I click on the next button nothing happens(when no namespace choosed).

![image](https://user-images.githubusercontent.com/32871167/127526408-fd7364da-44b1-4c25-a441-d3f8a5d49ba5.png)
I want some error message why the GUI dont like that email.

![image](https://user-images.githubusercontent.com/32871167/127526928-51b282e8-ef2b-4003-81e5-2ca6e47a2080.png)
Search filed could be bigger and could react to enter key

![image](https://user-images.githubusercontent.com/32871167/127527435-7031fb05-bcfa-4c7b-82f4-629df82c5046.png)
Instead of the trash can I would like here more the "cross"
You could add the id of the user here also
Also when there is only one name I would just disable the icon for remove and add tooltip why is it disabled.

![image](https://user-images.githubusercontent.com/32871167/127528119-65353d5f-34e4-4003-8643-f62a7f038f37.png)
Add gap between these two elements 

![image](https://user-images.githubusercontent.com/32871167/127528446-f46aebd8-69b6-4930-a37b-4e1eebe62575.png)
I feel like the gap between these two elements is too big

![image](https://user-images.githubusercontent.com/32871167/127528620-ae9ed4a9-0a49-480f-845b-52ebf097b8ae.png)
When no namespace is selected its really weird that the third "step" in stepper is missing and when choosing some other namespace it suddenly out of nowhere appears. The number of steps should be constant no matter what. On the last step there could be just some text that tells the user he dont have to set the password

![image](https://user-images.githubusercontent.com/32871167/127529590-a34ca33d-637d-4518-8216-e5a532019377.png)
I would like here if the no namespace is selected the login field would be just disabled(with tooltip why it is disabled) not completely hided. Again I found it weird when somehow suddenly out of nowhere appears some input field

2021-08-02 13:13 UTC, xkureck requested changes

2021-08-04 11:00 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/128168970-a534dfc6-f7c6-41b8-86e4-19ed38d63742.png)
The password which is optional I would still have something else. I would inspire in our create sponsored member dialog 
![image](https://user-images.githubusercontent.com/32871167/128169318-d9e79e91-1417-4f9b-9939-5beeafb04725.png)
where there is checkbox and if its checked the password input is disabled. The text next to the label could be something like: "Generate random password"

![image](https://user-images.githubusercontent.com/32871167/128169735-93e9aa96-148c-4abf-98b9-a3835e584d46.png)
Also use green button for "next" as it is in create sponsored member dialog

2021-08-09 12:06 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/128702055-11d49020-3e0b-476e-981d-d267411df8d6.png)
just when i open the dialog some error appears

![image](https://user-images.githubusercontent.com/32871167/128703248-a99589f7-6071-4d62-8c10-4309dcf2557c.png)
I would add the second option this way

![image](https://user-images.githubusercontent.com/32871167/128702213-436889d4-a052-41f5-a9b9-97b4757215f6.png)
When login is checked you could add some debounce time to the input field so the gui dont have to do so much calls to backend

2021-08-10 14:20 UTC, xkureck requested changes
![image](https://user-images.githubusercontent.com/32871167/128878597-3e666fad-c99a-4ce9-b1be-6c2be1c31603.png)
just remove the "optional" from the name of the stepper and merge it

![image](https://user-images.githubusercontent.com/32871167/128879200-cdfc1c18-f697-4f8c-b362-3918ac7d1642.png)
fix eslint problems, also rebase, some eslint problems are already fixed I believe

![image](https://user-images.githubusercontent.com/32871167/128880779-20617574-f095-4ea0-82dc-8f8a665a1c81.png)
I selected some namespace then I typed something to passwords inputs and then I selected no namespace and the passwords inputs stay as they are

2021-08-10 14:20 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
> +                  <mat-icon style="margin-bottom: 6px;">close</mat-icon>
no css style in the html please

2021-08-10 14:20 UTC, xkureck commented on apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
> +          [selection]="selection"></perun-web-apps-members-list>
```suggestion
          <perun-web-apps-members-list
            *ngIf="firstSearchDone"
            [disableRouting]="true"
            [displayedColumns]="['checkbox', 'id', 'fullName']"
            [members]="members"
            [pageSize]="pageSize"
            [selection]="selection"></perun-web-apps-members-list>
```

2021-08-11 11:36 UTC, xkureck approved these changes

2021-08-11 11:37 UTC, merged