feat(admin): allow setting member expiration in future
CESNET/perun-web-apps pull request #862
Opened 2021-09-22 11:16 UTC by xkostka2

* if a member is in 'EXPIRED' state, changing his/her expiration to a date in future or to 'never' now changes also member's status to 'VALID'

2021-09-22 12:09 UTC, bodnara requested changes
When changing expiration of an expired member it is now possible to choose dates both form past and the future. What I undestood was to only make future dates avaliable but maybe I am mistaken.

2021-09-22 12:09 UTC, bodnara commented on apps/admin-gui/src/app/shared/components/member-overview-membership/member-overview-membership.component.ts
> +        }
Honestly this is not a good code practice. My suggestion is to return tuple (success, meber) from the dialog.

2021-09-22 12:09 UTC, bodnara commented on apps/admin-gui/src/assets/i18n/en.json
>      },
I would change this to be something like "This action will result in ...".

2021-09-23 11:06 UTC, bodnara approved these changes

2021-09-24 11:37 UTC, xkureck approved these changes

2021-09-24 11:37 UTC, merged