feat(admin): support list and map application form item
CESNET/perun-web-apps pull request #995
Opened 2022-03-16 12:57 UTC by bodnara

* allow creating list and map form items
* properly show them on preview
* allow editing of these items

2022-03-17 09:22 UTC, mattjoke approved these changes

2022-03-17 10:21 UTC, HejdaJakub requested changes
I think you should also add these two types to the property `typesWithDisabled` in the `edit-application-form-item-dialog.component.ts`. There are also properties like `typesWithUpdatable` and `dependencyTypes`, but I am not sure if we want the list and map to be updatable or to be a dependency type, but the option for disable them there probably should be.

2022-03-17 10:21 UTC, HejdaJakub commented on apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.html
> +          *ngIf="applicationFormItem.type === 'MAP_INPUT_LIST' &&
Map item isn't visible on the preview.
```suggestion
          *ngIf="applicationFormItem.type === 'MAP_INPUT_BOX' &&
```

2022-03-21 08:58 UTC, HejdaJakub commented on apps/admin-gui/src/assets/img/PerunWebImages/home.svg
> +</svg>
This probably shouldn't be a part of this PR? Otherwise, it looks good.

2022-05-23 10:01 UTC, HejdaJakub approved these changes

2022-05-23 10:11 UTC, merged